### ISSUE TITLE
status bar random behavior

### ISSUE THREAD

**Issue by teotwawki16** [jarun/nnn#239] opened 2019-04-06 05:02 UTC
#### Info
[ x ] Operating System: arch linux
[ x ] Desktop Environment: n/a (i3-gaps)
[ x ] Terminal Emulator: st
[ x ] Shell: bash
[ x ] Custom desktop opener (if applicable): perl-file-mimeinfo (mimeopen)
[ x ] Issue exists on `nnn` master: yes

#### Issue
The status bar goes to the middle randomly when opening nnn using a keybinding.

#### How to reproduce
1. Have this in your i3 config:
`bindsym $mod+f --no-startup-id st -e nnn`
2. Open a terminal or any other program.
3. Use the binding.

Note: Sometimes, the status bar goes to the bottom (which is the intended behavior).

#### Screenshot
https://i.imgur.com/o9xr0x6.png

**Comment by jarun** [comment] 2019-04-06 06:52
Does this happen only when you start `nnn`?

What happens when you press `^L`?

I don't use i3 myself. I think the problem is in `redraw()` function `nnn` reads half the LINES for y.

**Comment by jarun** [comment] 2019-04-06 06:53
What happens if you use some other terminal than `st`?

**Comment by teotwawki16** [comment] 2019-04-06 07:09
> `^L`

Nothing happens.
> other terminal than `st`

I tried `urxvt` and `termite`. It doesn't happen. Is it a problem on `st`?

**Comment by jarun** [comment] 2019-04-06 07:50
Does this happen every time you start `nnn`? If yes, then it is probably `st` issue.

If not all time issue, try `urxvt` or `termite` for a few days and we can confirm.

**Comment by teotwawki16** [comment] 2019-04-07 06:01
Termite did it. But after about a split second, then status bar then went back to the bottom.
https://i.imgur.com/ZVQeJIo.png

**Comment by jarun** [comment] 2019-04-07 06:43
That means st is on updating the new geometry. Shall I close the issue?

**Closed by jarun** 2019-04-07 06:43 UTC
Labels: help wanted
