### ISSUE TITLE
Issue with the pager (not sure it’s NNN related)

### ISSUE THREAD

**Issue by Hibou57** [jarun/nnn#75] opened 2018-01-06 17:13 UTC
It seems random, I can’t tell how to reproduce, but I noticed output from NNN using the pager, which is Less for me, often starts with a truncated display, sometime scrolling redraw the part left blank, but sometimes too, it has issue with scrolling. It seems to not know how many lines are available for output. As an example, I may have to retry Shift-F multiple times on an archive to be able to list its content properly.

I can’t tell it it’s an issue with Less or with NNN. What’s sure, is that Less works normally outside of NNN.

**Comment by jarun** [comment] 2018-01-06 20:08
Which version of `nnn`? How big is the archive?

I think it would be a good idea to do some modifications in `get_output()` - if pager is set, write the command output to a tmp file (as is `show_stats()`) and then render it in the pager.

if you are interested, please raise a PR. Otherwise, I will add it to the ToDo list. For me, I can't commit this change right away.

**Comment by Hibou57** [comment] 2018-01-06 21:31
Oops, sorry, forgot:

    $ nnn -v
    > 1.6

Rather small archive, but this also occurs with the integrated help, the one invoked on “ ? ”

**Comment by jarun** [comment] 2018-01-06 21:41
In that case I believe there's something else into play. I have never seen any issues with the help.

**Comment by jarun** [comment] 2018-01-06 21:41
Can you try `more` as the pager?

**Comment by jarun** [comment] 2018-01-06 22:11
Can you please try the following patch?

```
diff --git a/nnn.c b/nnn.c
index f1422e3..abd8b98 100644
--- a/nnn.c
+++ b/nnn.c
@@ -1499,7 +1499,8 @@ get_output(char *buf, size_t bytes, char *file, char *arg1, char *arg2, int page
        }
 
        /* In parent */
-       waitpid(pid, &tmp, 0);
+       while (waitpid(pid, &tmp, 0) == -1);
+       fflush(NULL);
        close(pipefd[1]);
 
        if (!pager) {
@@ -1523,7 +1524,7 @@ get_output(char *buf, size_t bytes, char *file, char *arg1, char *arg2, int page
        }
 
        /* In parent */
-       waitpid(pid, &tmp, 0);
+       while (waitpid(pid, &tmp, 0) == -1);
        close(pipefd[0]);
 
        return NULL;
```

I can't reproduce this on my system (Ubuntu 16.04, i7 gen 7, SSD) but this patch will ensure the buffers get flushed before they are read from stdin.

**Comment by Hibou57** [comment] 2018-01-06 22:28
I tried to `update‑alternative --config page` to use `less`, `more`, `most` and `pg`, and it’s the same.

But I have news. I start `nnn` using one of two way. The first is the `nnn` command from a terminal, the second is via a keybinding in my windows manager (i3WM). It start a scripts containing this:

    #!/bin/sh
    exec gnome-terminal -e nnn

This is so, to have a terminal, since `nnn` requires one. I just noticed the issue occurs only when `nnn` is started this way. And I also checked it’s the same if I try to run this script directly, I mean not using the keybinding.

**Comment by Hibou57** [comment] 2018-01-06 22:32
My Ubuntu is Ubuntu Xenial (16.04) 32 bits. I will try the patch later and will tell.

**Comment by jarun** [comment] 2018-01-06 22:41
I tried `terminator -e nnn` and I don't see any issues. Can you try dropping the `exec` from the script?

**Comment by Hibou57** [comment] 2018-01-06 23:57
Hi, I’m back (and it’s night time here :D )

Just tried the patch, and its the same. I applied the patch manually, because the `patch` command failed to apply it.

I tried removing `exec` in the script, and it’s the same. May be that’s not NNN related. It seems to mess up with the number of lines in the terminal.

Don’t bother too much, since the error may as much be in the terminal. I will try with other terminal emulator and will tell.

**Comment by jarun** [comment] 2018-01-07 03:26
OK. So I'm closing the defect with this update.

BTW, an alternative to spawning a new terminal each time is a lightweight tabbed drop-down terminal. The advantage is - you never lose your context. I use the drop-down mode of `xfce4-terminal` nowadays. terminator (with both split and tab support) and altyo are great too!

**Closed by jarun** 2018-01-07 03:26 UTC
