### ISSUE TITLE
go in and return out of dir get me on a different row

### ISSUE THREAD

**Issue by pizdjuk** [jarun/nnn#650] opened 2020-06-11 14:48 UTC
[x ] Operating System: linux
[x ] Desktop Environment: mate
[x ] Terminal Emulator: urxvt
[x ] Shell: bash
[ ] Custom desktop opener (if applicable):
[ ] Program options used:
[ ] Configuration options set:
[x ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

go into some directory dir1 (l), select some file with a cursor(jjjj), go out (h).
we are in the parent directory exactly on a row, which was pointed when we were into the dir1.

The expected behaviour is that the cursor position in a parent directory memorized when we are going into some directory.

**Comment by jarun** [comment] 2020-06-11 14:55
> The expected behaviour is that the cursor position in a parent directory memorized when we are going into some directory.

The behaviour is to highlight the directory you entered when you come out of it.

So in this case, when you come out of dir1, dir1 should be highlighted. If that's nto the case, share and asciicast.

**Comment by jarun** [comment] 2020-06-11 16:40
Closing this as explained.

**Closed by jarun** 2020-06-11 16:40 UTC
Labels: bug

**Comment by pizdjuk** [comment] 2020-06-13 00:44
the highlited directory is correct, when I'm out of the dir1. But the position is "incorrect". For example, dir1 is in a fifth row, then entering into the dir1 and coming out of dir1 makes the highlited dir1 appears in a first row.

**Comment by jarun** [comment] 2020-06-13 02:23
What's your sort order?

**Comment by jarun** [comment] 2020-06-13 03:36
I think you understand by now that I can't reproduce this. If you cannot provide a 100% way to reproduce the issue I cannot debug it.

Please test on master without:

- any `nnn` program options
- any `nnn` configuration settings

and see if you can reproduce it.

**Comment by toddyamakawa** [comment] 2020-06-13 23:27
I'm also unable to reproduce this issue. I played around with this for a little bit but I can't get the row of the active directory to change.

**Comment by pizdjuk** [comment] 2020-06-16 11:40
The bug is triggered, when there are a lot of subdirectories. start nnn, scroll down till the list of directories begins to scroll, then enter some directory, go out. The cursor will appear at the very top of the list.

**Comment by pizdjuk** [comment] 2020-06-16 11:40
I can make a screencast if needed

**Comment by jarun** [comment] 2020-06-16 13:13
Got it. When you scroll/pgup/pgdn the scrolloff decides the position. The position is not retained and when you get back into the parent directory it's decided by the index of the file among other files.

**Comment by pizdjuk** [comment] 2020-06-17 09:52
So, I'm a bit confused.... will it be fixed, or is it a feature? :)

**Comment by jarun** [comment] 2020-06-17 11:12
It's a feature.

**Comment by jarun** [comment] 2020-06-17 11:13
or, the expected behaviour in this case.

**Comment by pizdjuk** [comment] 2020-06-17 14:18
it would be nice to have an option to change this behavior, because it is a little bit confusing. I mean, VC, NC, MC, TC behaves on the described way (memorize the position of a cursor in every directory). And only nnn behaves different.

**Comment by pizdjuk** [comment] 2020-06-17 14:54
confusing I mean, that when I'm browsing directories, One expects to find a cursor on the same places where it was.

**Comment by jarun** [comment] 2020-06-17 15:10
That was the earlier behaviour in nnn as well, the position was based on the index always. however, there were pros and vons and we wanted to have scrolloff so ot was changed. As it's been this way for a long time, I would prefer to retain it. As the current item ia highlighted, there's no issue with identifying it.
