### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#1292] opened 2022-01-23 15:24 UTC
Rolled from #1219.

### Cooking

- disable filter info if file details (option `-i`) enabled
- open previous active context on context quit
- switch <kbd>^J</kbd> and <kbd>+</kbd> functionality:
  - <kbd>+</kbd>: toggle file selection
  - <kbd>^J</kbd>: toggle auto-jump on file open
- allow symlink creation with name `@` to a single file (#1345)
- clear selection on successful operation at native prompt with "%j" (#1330)
- reverse timestamps of entries modified/created within 5 minutes
- avoid using non-portable `xargs` flags on macOS (#1299)
- quitcd script for Elvish shell > 0.17.0 (#1344)
- plugin `openall` to open selected files together (#1333)
- plugin `gitroot` to jump to git root directory from a subtree
- plugin `gsconnect` to send the selected files to Android using gsconnect
- icon for opus and webp files
- `preview-tui` - fix gif conversion and whitespace name
- `preview-tui` - add support for windows terminal split
- `preview-tui` - djvu file previews
- `nuke` - add support for `imv` when named _imv_
- `gsconnect` - support connection to multiple devices
- export `NNN_INCLUDE_HIDDEN` to plugins (#1308)
- respect `NNN_TRASH` in `.nmv` (#1306)
- add GNU sed as a dependency with support for env var `SED`
- use bold `>` to point at current entry in detail mode
- add 2 spaces after icons for better visibility
- documentation refresh
- make option `O_NOSORT` to load directories unsorted on entry

### Up for grabs

None open at the time.

For anything else please discuss in this thread.

**Contribution [guideline](https://github.com/jarun/nnn/blob/master/misc/CONTRIBUTING.md).**

**Comment by rieje** [comment] 2022-02-04 16:20
Is it possible to save nnn session automatically without `Q`, e.g. if closed terminal without manually exiting nnn?

Also would like the option of `-S` (persistent session) to not save the session if all contexts are closed. That would work nicely for my wrapper script where first argument would be checked if it's a directory/file and if so, open it with nnn, otherwise, create a session. Sometimes I realize I don't want the session saved anymore after working with it, so it would be nice to quit all contexts to prevent the session from being saved instead. I don't see any benefits of saving a session when all contexts are closed and this would be an option anyway.

Would be nice to be able to "redraw" a filtered list.

How does nnn decide which context to focus after closing a context? Did a quick test and it seems it doesn't focus on n-1 context (closing 4th context focuses on 1st one despite 2nd/3rd opened) nor does it focus on most most previous context. The latter or n-1 context is preferable.

**Comment by jarun** [comment] 2022-02-05 18:26
> Is it possible to save nnn session automatically without Q, e.g. if closed terminal without manually exiting nnn?

Does the following patch help?

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 8673207..df059b9 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -6715,7 +6715,7 @@ begin:
 nochange:
                /* Exit if parent has exited */
                if (getppid() == 1)
-                       _exit(EXIT_FAILURE);
+                       return EXIT_FAILURE;
 
                /* If CWD is deleted or moved or perms changed, find an accessible parent */
                if (chdir(path) == -1)
```

> Also would like the option of -S (persistent session) to not save the session if all contexts are closed.

This is an ambiguous behaviour. Some user may be working with only 1 context and she may want to save the context when she exits. The current behaviour is exactly as advertised and will not be changed.

> Would be nice to be able to "redraw" a filtered list.

Why? If you have lost the filtered listing, you can apply the last filter again by pressing <kbd>^U</kbd> at the filter prompt.

> How does nnn decide which context to focus after closing a context?

Currently it focuses on the next active context by number. We can change the behaviour to focus on the previous active context by number. We don't track the history of context usage.

**Comment by jarun** [comment] 2022-02-05 18:55
> We can change the behaviour to focus on the previous active context by number.

Implemented at commit 23b54ba0cf968d7c3c5973642186223c70aa9cf6.

**Comment by rieje** [comment] 2022-02-10 23:54
> Does the following patch help?

Just tested, doesn't seem to work (applying patch directly didn't work for me, I had to generate same patch manually (maybe tabs/spaces issue?).

> This is an ambiguous behaviour. Some user may be working with only 1 context and she may want to save the context when she exits. The current behaviour is exactly as advertised and will not be changed.

Oh yea, not suggesting the current behavior to change as it's simple/intuitive, just wish for an additional option for the behavior described.

> Why? If you have lost the filtered listing, you can apply the last filter again by pressing ^U at the filter prompt.

Didn't realize this (^L), nice.

> We can change the behaviour to focus on the previous active context by number.
> Implemented at commit 23b54ba.

Works great.

**Comment by jarun** [comment] 2022-02-11 00:12
> Just tested, doesn't seem to work (applying patch directly didn't work for me, I had to generate same patch manually (maybe tabs/spaces issue?).

If this doesn't work then I don't know how to do that.

> Oh yea, not suggesting the current behavior to change as it's simple/intuitive, just wish for an additional option for the behavior described.

We can't keep adding options for everything. Thanks!

**Comment by rieje** [comment] 2022-02-12 17:31
In batch rename, deleting line of filename `rm`'s the file. Instead, it should respect `$NNN_TRASH`.

**Comment by jarun** [comment] 2022-02-12 23:19
@KlzXS I think it's a fair request to trash when defined. Can you please take a look?

**Comment by LordRishav** [comment] 2022-02-27 06:20
Is it possible to make nnn sort by 'creation time'? As far as I know, it only supports sorting by modification time, and it will be good if nnn supported sorting by creation time as well. `ls -lt --time=birth` on coreutils 8.32+ works for the purpose on the [supported filesystems](https://unix.stackexchange.com/questions/7562/what-file-systems-on-linux-store-the-creation-time).

**Comment by jarun** [comment] 2022-02-27 08:41
I don't think there's a single reliable way to get it yet.

**Comment by LordRishav** [comment] 2022-02-27 09:25
Hmm, I have not tried the `ls` flag on a filesystem other than ext4 really, so I too can't be sure about whether it works reliably everywhere. On ext4 however, `stat -c %w file` (like in the hyperlink above) does show the crtime of a file as it was created.

When I tried to find other file browsers that do support such a feature, I found [ranger](https://github.com/ranger/ranger) does. However ranger is like HUGE so you may not want to implement the feature if you think it will require too much code.

**Comment by jarun** [comment] 2022-02-27 13:45
No, we don't want to implement filesystem-specific hacks in `nnn`. Thanks!

**Comment by rieje** [comment] 2022-03-02 00:33
`^I` binding is not documented? Pressing repeatedly looks like it just cycles between active contexts but for one of these contexts it starts a filter.

I only found out because when I press `l` to open a file, it opens the file but nnn starts a filter on one of the contexts. If I exit out of that filter and `l` to open another file, same thing. I can toggle off this undesirable behavior by pressing `^I`, so it seems `^I` is a toggleable feature and I must have accidentally triggered this keybinding initially.

If I run nnn without options, I am not able to reproduce the above behavior-- `^l` will simply cycle through the contexts.

**Comment by jarun** [comment] 2022-03-02 01:27
There's no ^I, looks like you are talking about ^N.

**Comment by rieje** [comment] 2022-03-02 01:54
I am aware of ^N and it's correct behavior is different than ^I. If ^I is supposed to do nothing, then I will file a bug when I have the time. I also found ^5 has the behavior of ! (go to shell) that's not documented.

**Comment by jarun** [comment] 2022-03-02 03:25
^I or ^5 codes duplicating other codes is not an `nnn` issue. You can check with the ncueses guys and proceed.

**Comment by muppi090909** [comment] 2022-03-04 16:06
How do I get ```bat``` or in Ubuntu *which i am currently using* ```batcat``` to preview my text/code files. Also more importantly should this be added to the wiki or at least the plugin docs for preview-tui.

**Comment by replica9000** [comment] 2022-03-04 21:07
I noticed when I use `tree` (or run a script that uses tree) from within `nnn`, tree outputs in json format as if I was calling `tree -J`.  I'm not seeing any environmental variables or aliases causing tree to output this way.

**Comment by N-R-K** [comment] 2022-03-04 21:12
@replica9000 either upgrade to the latest tree version or compile nnn from master. https://github.com/jarun/nnn/issues/1291

**Comment by replica9000** [comment] 2022-03-04 21:21
@N-R-K Thanks for the info.  I've already compiled `nnn` from master.  I've upgraded `tree` from 2.0.1 to 2.0.2, and tree works as expected now.

**Comment by muppi090909** [comment] 2022-03-05 02:36
How do I get ```bat``` or in Ubuntu *which I am currently using* ```batcat``` to preview my text/code files. Also more importantly should this be added to the wiki or at least the plugin docs for preview-tui.

**Comment by pvx-** [comment] 2022-03-07 11:10
> I am aware of ^N and its correct behavior is different than ^I I'm experiencing. If ^I is supposed to do nothing, then I will file a bug when I have the time. I also found ^5 has the behavior of ! (go to shell) that's not documented, so that might be related.

Most terminals send the same character for Tab and ^I, see for example [here for more info](https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode). I don't know about ^5, but I suspect it will be something similar.

**Comment by pvx-** [comment] 2022-03-07 11:13
One small patch I always apply, please consider including it:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 878e15d8..2fcee449 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -1454,7 +1454,7 @@ static char confirm_force(bool selection)

        int r = get_input(str);

-       if (r == ESC)
+       if (r == ESC || r == 'n' || r == 'N')
                return '\0'; /* cancel */
        if (r == 'y' || r == 'Y')
                return 'f'; /* forceful for rm */
```

"n" is more convenient than ESC for touch-typists and I press "x" over wrong file quite often ;).

**Comment by jarun** [comment] 2022-03-13 07:09
Pushed at commit https://github.com/jarun/nnn/commit/d38841d5f327f9ae4db6ca40a286c400b422b102.

**Comment by page-down** [comment] 2022-03-18 10:50
I noticed that due to CWD notifications (OSC 7) is not escaped for URL, the terminal parses some paths (e.g. `/tmp/%20test/`) to a different path than the original.

I saw the previous discussion
https://github.com/jarun/nnn/pull/1148#issuecomment-908469643

If it is not worthwhile to implement the full url encoder (all except `a-zA-Z0-9_.~-`),
is it possible to just replace `%` with `%25` as in the following example?
https://codeberg.org/dnkl/foot/wiki#how-to-configure-my-shell-to-emit-the-osc-7-escape-sequence

Thank you.

(Recently kitty terminal added support for OSC 7 and I'm testing the functionality.)

**Comment by jarun** [comment] 2022-03-18 13:20
No plans. Thanks!

**Comment by pvx-** [comment] 2022-03-23 16:56
Non-blocking actions (requested in #1328) are sometimes useful and can be easily done if you use tmux - I have custom plugin (based on rsynccp) for copying huge files (`;p` instead of `p`) that splits current window and runs rsync there - so I can continue using nnn and monitoring copy progress at the same time.

My first idea was using named plugins (like `.cp/.mv/.rm`) instead of cp/mv/rm, like you already do with advcpmv for `-r`, but that may be too dangerous (users reporting their own bugs in these plugins as nnn bugs :)). Maybe adding info about using plugin with tmux for non-blocking actions to the wiki will be sufficient and you can refer further requests of this feature there.

**Comment by greenfoo** [comment] 2022-04-02 09:18
Feature request:

In #899 I asked about being able to automatically close nnn when a file was opened. Back then I was suggested to use the [file picker option](https://github.com/jarun/nnn/wiki/Basic-use-cases#file-picker) which is what I have been doing since then. *However* there is one thing that doesn't seem to work in "file picker mode": copying/moving files.

In other words, if I run "nnn -p -" I can not select with "space" and then copy/move with "y","v" because the selection is always empty (I guess this happens because un "file picker mode" the selection is used to decide what to print when "nnn" exists).

So... would it be possible for "copy"/"move" to work while in "file picker mode"? And, if not, maybe it is worth to reevaluate the patch in #899 that closes "nnn" after openin a file in "normal mode"?

Thanks!

**Comment by N-R-K** [comment] 2022-04-02 09:33
> In other words, if I run "nnn -p -" I can not select with "space" and then copy/move with "y","v" because the selection is always empty (I guess this happens because un "file picker mode" the selection is used to decide what to print when "nnn" exists).

That's weird, I can copy/move files inside `nnn.vim` just fine, which uses the picker mode.

Trying it out, I can reproduce this with `nnn -p -` and `nnn -p /dev/null` however `nnn -p /tmp/test` works fine with copy/move.

**Comment by greenfoo** [comment] 2022-04-02 09:57
Good finding! That makes sense: it looks like in "file picker" mode the selection file is overwritten by whatever is provided in the command line:
![selection](https://user-images.githubusercontent.com/42691086/161377922-510227f5-2720-44eb-ba5c-aef93fc4ab05.png)

This explain why it does not work when using `nnn -p -` or `nnn -p /dev/null`.

Maybe a tmp selection file can be used in those cases until `nnn` exits and prints the selection to the "real" fd provided in the command line.

**Comment by jarun** [comment] 2022-04-02 13:38
Sorry, I don't want to complicate this. `nnn -p -` does exactly what it is supposed to do - pick files and write to stdout. Please use a separate output file to use as selection if you want to use functionality that needs the selection file.

Also, did you notice that pressing `Q` to quit also writes the selection to stderr? Perhaps this can help in your case.

**Comment by greenfoo** [comment] 2022-04-02 16:42
Sure, no problem. I can work around using `nnn -p /tmp/somefile.txt` for my use case. Thanks!

**Comment by rieje** [comment] 2022-04-03 05:30
Is there a reason why QSORT is not the default and will it ever be?

**Comment by jarun** [comment] 2022-04-03 06:37
No reason other than it came later. There is no definitive proof that it is faster in all scenarios and if you are interested in it probably you also know how to compile `nnn` from source.

**Comment by rieje** [comment] 2022-04-08 21:57
Following the example from the README, `export NNN_PLUG='m:-!|mediainfo $nnn'` and then running the plugin, it does not show the output of mediainfo. Instead, it shows:

    /tmp/.nnn1mtjZb (END)

and then pressing a key will show an empty output.

Any ideas?

**Comment by jarun** [comment] 2022-04-09 00:12
@raj-magesh VS Code is a GUI tool. You might have some luck with the documentation here: https://github.com/jarun/nnn/wiki/Advanced-use-cases#browser-integration

however, I haven't come across anyone who has tried it before. Do let us know if you are able to achieve that.

@rieje which version of `nnn` are you using? Does running mediainfo directly on the file work? It appears `nnn` is trying to pipe the output however there was none.

**Comment by rieje** [comment] 2022-04-09 03:20
> @rieje which version of `nnn` are you using? Does running mediainfo directly on the file work? It appears `nnn` is trying to pipe the output however there was none.

Latest version 4.4. Yes, mediainfo works directly on file. I don't know if it has anything to do with it but the output of mediainfo is long and the `/tmp/.nnn1mtjZb (END)` shows up maybe 5 lines starting from the top. I was thinking maybe I need to scroll up but pressing any key shows `(END)` at the end of the line and the first column full of `~` in an otherwise blank output.

**Comment by jarun** [comment] 2022-04-09 03:29
Sorry, I'm unable to reproduce this.

**Comment by gavieira** [comment] 2022-04-11 15:29
Hello! Thanks for the amazing tool.

[This link](https://github.com/jarun/nnn/wiki/concepts#prompts) from the wiki states that: 

"The prompts (except the filter prompt) support readline-like command-line shortcuts. Enter or ^D at the empty prompt (except the filter prompt) exits the prompt.
Key ^L clears and Esc exits all prompts."

Is there some reason to this behavior? I'd personally like to type a substring, have Enter exit the command prompt and then select the file of interest.

Though I tried, I still haven't managed to get the desired behavior by changing the bindings in the source code yet. I would really appreciate if someone could give me a hint on how to achieve this or point me to a fork that does that.

**Closed** 2022-04-26 13:30 UTC
Labels: planning
