### ISSUE TITLE
Special file names are not aligned in detail view

### ISSUE THREAD

**Issue by ada-43** [jarun/nnn#484] opened 2020-03-03 20:46 UTC
#### Environment details
[x] Operating System: linux
[x] Issue exists on `nnn` master

Special file names (symlinks, etc.) are shifted one position to the left.

**Comment by 0xACE** [comment] 2020-03-04 00:27
I can't reproduce this in `master`.

Could you submit extra details which you might find relevant? Maybe even a screenshot?

**Comment by jarun** [comment] 2020-03-04 00:49
@ada-43 Please confirm this is fixed on master.

@0xACE this is in detail mode due to a recent regression.

**Closed** 2020-03-04 00:48 UTC

**Comment by 0xACE** [comment] 2020-03-04 01:21
My bad seems like i forgot to `fetch origin` before i rebased my master...

I noticed you added colours to `symlinks` and what not.

On my local branch i have a poor implementation for colouring files that are eXecutable, do you have plans to adding it to upstream?

Also I'd like to point out that the color the symlinks for directories on my cli are very difficult to see on dark backgrounds (I have nnn set to blue colorscheme)

![color](https://user-images.githubusercontent.com/1482942/75835161-0eaef700-5db6-11ea-9181-bf2456461c1d.png)
*image showing difficulty with colortheme*

![exec](https://user-images.githubusercontent.com/1482942/75835287-5b92cd80-5db6-11ea-9141-19bc0294057b.png)
*image showing how i view exectubles (which i frequently execute with `C`)*

Personally this isn't as issue to me, but I thought I'd give you a heads up just in case.

**Comment by jarun** [comment] 2020-03-04 01:25
> Also I'd like to point out that the color the symlinks for directories on my cli are very difficult to see on dark backgrounds (I have nnn set to blue colorscheme)

names of symlinks (to files or dirs) and hard links are dimmed on purpose. I had no other way to distinguish links. How about underlining then?

> image showing how i view exectubles (which i frequently execute with C)

What happens if the context color is green and the first file after the list of dirs is an executable? The * won't be a quick guess.

**Comment by 0xACE** [comment] 2020-03-04 01:36
> names of symlinks (to files or dirs) and hard links are dimmed on purpose. I had no other way to distinguish links. How about underlining then?

I'm not a fan of underlining. But do as you please, I'll manage myself. Atm, I don't have a suggestion for this particular problem. I am aware of blue not being the best colour to choose, but I find it relaxing on my screen.

> What happens if the context color is green and the first file after the list of dirs is an executable? The * won't be a quick guess.

Oh yeah, I forgot about that part, it's true... Since it's a personal build it didn't cause a issue for me. nvm it then...

I'd guess it's too convoluted to ask the user to specify all of these colours...

Anyhow, I'm noticing I'm making too many mistakes which is probably a sign that I should get some sleep. Good night <3

**Comment by jarun** [comment] 2020-03-04 01:41
Have a good sleep!

**Comment by ada-43** [comment] 2020-03-04 12:11
Shifted names fixed, thank you.
