### ISSUE TITLE
mouse does not work in xterm + nvim's builtin terminal

### ISSUE THREAD

**Issue by haolian9** [jarun/nnn#1521] opened 2022-11-13 16:41 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: linux
- [x] Desktop Environment: none; x11+i3wm
- [x] Terminal Emulator: xterm
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
* nnn version: v4.6
* TERM env: not set in my personal config, I let the terminal decide
* `xterm -e 'nvim --clean +"terminal nnn"'`

**Comment by jarun** [comment] 2022-11-13 16:47
Mouse support can be compiled out: https://github.com/jarun/nnn/wiki/Developer-guides#compile-out-mouse-support

Please check if that's the case.

**Comment by luukvbaal** [comment] 2022-11-13 16:49
This has been discussed before. The `TERM` environment variable needs to be passed along to the embedded terminal. Then it will work. IDK if this can be circumvented on the nnn side, I think last time we decided against.

**Comment by jarun** [comment] 2022-11-13 16:50
Did we document it somewhere? If not, can you please add?

**Comment by luukvbaal** [comment] 2022-11-13 16:50
Sounds like it should actually be fixed on the vim side perhaps.

**Comment by luukvbaal** [comment] 2022-11-13 16:53
Previous discussion: https://github.com/jarun/nnn/commit/00c73512b98ad0e02068f38051664ca3e23997cc

**Comment by jarun** [comment] 2022-11-13 17:02
Thanks! If `TERM` is not available, I don't think we can guess anything.

**Comment by haolian9** [comment] 2022-11-13 17:19
thanks for the replies!
well in my tests, it just need `\x1b[?1002h` for mouse button events.

**Comment by haolian9** [comment] 2022-11-13 17:23
about the "set TERM" solution, i have tested it in konsole and it does not seem to work. (to be exact, using nvim's builtin terminal inside konsole)

**Comment by N-R-K** [comment] 2022-11-13 17:28
> about the "set TERM" solution, i have tested it in konsole and it does not seem to work. (to be exact, using nvim's builtin terminal inside konsole)

Where exactly are you setting `TERM` ? The problem was that nvim's builtin terminal doesn't forward the env vars. Try running something like this: `vim --clean +"terminal env TERM=xterm nnn"`

**Comment by haolian9** [comment] 2022-11-13 17:44
my steps are:
* launch konsole
* `$ echo TERM` -> `konsole-256color`
* `$ nvim` # i need nnn.nvim so no `--clean here`
* `:lua require'nnn'.setup()` # nvim cmds
* `:NnnExplorer` # nvim cmds
* `$ cat /proc/$(pgrep nnn)/environ | tr -s '\0' '\n' | grep TERM` -> konsole-256color

using nvim barely:
* launch konsole
* `$ echo TERM` -> `konsole-256color`
* `$ nvim --clean`
* `:terminal` # nvim cmds
* `$ TERM=xterm nnn` # runs in nvim's builtin terminal

and either of them supports mouse click/scroll.

**Comment by haolian9** [comment] 2022-11-13 17:59
maybe that's a problem of libvterm which is used to impl nvim's builtin terminal.
@leonerd sorry to ping you

**Comment by N-R-K** [comment] 2022-11-14 04:08
Okay, I can reproduce it on `vim` and `xterm` too. Doesn't seem to be `TERM` related, this seems like a different problem this time.

```
[nnn nrk]~> vim --version | head -n 1
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 26 2022 21:16:10)
[nnn nrk]~> xterm -v
XTerm(375)
```

**Comment by luukvbaal** [comment] 2022-11-14 10:48
mouse support in `btop` for example works fine even without exporting TERM. Perhaps it is something that should be fixed on our end?

**Comment by jarun** [comment] 2022-11-14 13:22
As I can see, the mouse click doesn't even register. Added a print at `SEL_CLICK`. Doesn't even print.

**Comment by jarun** [comment] 2022-11-18 00:48
Maybe it's due to:

    2097         mouseinterval(0);

Not sure. We had to do that to emulate the double click accurately and there's no going back. @0xACE 

In any case, this is not a major inconvenience since the use case is a corner one and `nnn` is much more productive in it's no-mouse avatar. I am closing this as won't-fix.

**Comment by jarun** [comment] 2022-11-18 00:48
And as I understand, there's the `TERM` workaround too.

**Closed by jarun** 2022-11-18 00:48 UTC
Labels: environment

**Comment by luukvbaal** [comment] 2022-11-18 00:52
IDK, @N-R-K mentioned [other-wise](https://github.com/jarun/nnn/issues/1521#issuecomment-1313066432) although it works fine on my end. I might yet look into it some time.

**Comment by jarun** [comment] 2022-11-18 01:50
👍 

BTW, do you want to add the patch for selection count reading into patch FW? I am planning a release. We can have it in.

**Comment by haolian9** [comment] 2022-11-18 02:17
oh well, thanks for your time.
