### ISSUE TITLE
recently upgraded, strange triangles appearing on left margin

### ISSUE THREAD

**Issue by protrolium** [jarun/nnn#1382] opened 2022-05-31 19:39 UTC
I upgraded from 4.0 > 4.5 and I am seeing some interesting GUI elements added. I skimmed through the release notes but there was so much to wade through that I wasn't sure which feature was responsible:

<img width="247" alt="Screen Shot 2022-05-31 at 12 34 20 PM" src="https://user-images.githubusercontent.com/4933883/171270615-fd5d65a9-57a6-43e3-9e90-ac5801b1a3ba.png">

The triangles persist into directories and sometimes seem to be pointing at nothing.

macOS 10.14.6 
iTerm 2 version 3.4.15

**Comment by jarun** [comment] 2022-06-01 03:07
I don't have macOS and I was unable to repro this on Ubuntu.

Also, there are certain information you need to provide which you have conveniently removed.

Please figure out the commit (between 4.4 and 4.5) which has caused this and get back.

**Comment by protrolium** [comment] 2022-06-01 18:45
Apologies. Complete system information below. 

Bear with me as downgrading with homebrew is a new process for me. It appears the upgrade overwrites the previous version, preventing `brew switch` 

- [ x ] Operating System: macOS 10.14.6
- [ ] Desktop Environment:
- [ x ] Terminal Emulator: iTerm 2 (3.4.15) 
- [ x ] Shell: bash
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: 
- [ x ] Configuration options set: NNN_OPTS="Fox"
- [ x ] Plugins are installed: NNN_PLUG='p:x2sel;y:cbcp;n:nuke;f:finder;d:diffs;t:nmount;r:renamer;l:launch;c:nbak'
- [ ] Issue exists on `nnn` master

**Comment by protrolium** [comment] 2022-06-01 19:14
I have determined it is the `-x` option in my config that is causing this mysterious triangle element in iTerm 2 (nnn 4.5)

Looks like I was experimenting with `-x` for copying the selection path to clipboard but it turns out I am not using it as often as I thought, so I will disable that option for now.

**Comment by ggustafsson** [comment] 2022-06-02 06:06
Maybe it is a iTerm 2 thing? I don't use it so I don't know.

nnn v4.5 from Homebrew + nnn compiled from source works fine for me (-x and -d both on and off).

Our setup differs greatly though:
- macOS v12.4
- Terminal.app v2.12.7

Adding this just in case it might be useful for someone someday.

**Comment by N-R-K** [comment] 2022-06-02 09:52
`-x` doesn't *just* copy selection, it does some other stuff too. I suspect the cause of your problem lies in here:

https://github.com/jarun/nnn/blob/01ab453cffd10a8ed3a25f7dbea1f4b042d88a8f/src/nnn.c#L1284-L1292

I suppose your terminal emulator doesn't support these escape sequences and is unable to cope with it gracefully. Try out some other terminal to see if the issue still persists or not.

**Comment by jarun** [comment] 2022-06-02 13:06
@N-R-K do these special sequences work on macOS at all?

**Comment by N-R-K** [comment] 2022-06-02 14:53
No clue, I don't use mac.

**Comment by jarun** [comment] 2022-06-02 16:13
Closing as there is a workaround (disabling the option). We can't handle every terminal quirk.

**Comment by ggustafsson** [comment] 2022-06-02 16:14
Title and CWD sync works fine in Terminal.app.
I'm not sure about selection sync. Should any selection end up in the clipboard without doing anything else?
I also don't understand the meaning of notis. Didn't notice any difference when moving files.

**Closed by jarun** 2022-06-02 16:13 UTC

**Comment by jarun** [comment] 2022-06-02 16:15
notis - notifications (on cp or mv)

**Comment by jarun** [comment] 2022-06-02 16:16
See plugin `.ntfy`.

**Comment by ggustafsson** [comment] 2022-06-02 16:18
Sweet! `.ntfy` works fine. Still not sure about the clipboard sync though.

**Comment by N-R-K** [comment] 2022-06-02 16:27
clipboard sync also requires a special plugin, consult the manpage.

**Comment by jarun** [comment] 2022-06-02 16:38
`.cbcp`.

**Comment by ggustafsson** [comment] 2022-06-02 16:40
All of it works just fine. iTerm 2 issue then.
