### ISSUE TITLE
dragdrop plugin cannot select multiple files inside nnn

### ISSUE THREAD

**Issue by akrifari** [jarun/nnn#917] opened 2021-03-25 12:47 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: `arch linux 5.11.8-arch1-1`
- [X] Desktop Environment: `i3 version 4.19.1`
- [X] Terminal Emulator: `termite v15`, `alacritty 0.7.2 (5ac8060b)`
- [X] Shell: `zsh 5.8 (x86_64-pc-linux-gnu)`
- [X] Custom desktop opener (if applicable): `nuke`
- [X] Program options used: `dex`
- [X] Configuration options set: 

```
NNN_OPENER=$HOME/.config/nnn/plugins/nuke
NNN_OPTS="dex"
NNN_COLORS="4321"
NNN_PLUG='f:fzopen;v:imgview;g:getplugs;c:diffs;d:dragdrop;x:_chmod +x $nnn;t:_tree -a $nnn'
NNN_BMS='h:~;p:~/Pictures;b:~/.local/bin'
NNN_FCOLORS='c1030402006006f7c6d6ab01'
```
- [X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

1. Make sure you have already install [dragon](https://github.com/mwh/dragon)
2. Clone the nnn repository
3. Build and run by using `make clean && make O_DEBUG=1 && ./nnn`
4. Select multiple files by pressing <kbd>space</kbd> or <kbd>m</kbd>
5. Run `dragdrop` plugin by its key
6. Press <kbd>s</kbd> to drag selection
7. Press <kbd>a</kbd> to process all selection files
8. See error

#### Related Images

![repro.gif](https://user-images.githubusercontent.com/33394747/112474303-0ac78b80-8da2-11eb-8a2c-1881fdf50a9d.gif)

#### Related Files

<details>
<summary>nnndbg</summary>

```
ln __line__: VERSION=3.6
ln __line__: g_tmpfpath=/tmp
ln __line__: tmpfplen=5
ln __line__: home=/home/akrifari
ln __line__: cfgpath=/home/akrifari/.config
ln __line__: cfgpath=/home/akrifari/.config/nnn
ln __line__: selpath=/home/akrifari/.config/nnn/.selection
ln __line__: opener=/home/akrifari/.config/nnn/plugins/nuke
ln __line__: getenv(envs[ENV_VISUAL])=(null)
ln __line__: getenv(envs[ENV_EDITOR])=nvim
ln __line__: editor=nvim
ln __line__: pager=less
ln __line__: shell=/usr/bin/zsh
ln __line__: getenv("PWD")=/home/akrifari/Documents/oss/nnn
ln __line__: COLORS=256
ln __line__: COLOR_PAIRS=32767
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=67979
ln __line__: __func__=redraw
ln __line__: path=/home/akrifari/Documents/oss/nnn
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
ln __line__: pid=17174
ln __line__: __func__=redraw
ln __line__: path=/home/akrifari/Documents/oss/nnn
ln __line__: pid=17182
ln __line__: __func__=redraw
ln __line__: path=/home/akrifari/Documents/oss/nnn
ln __line__: status=0
ln __line__: pid=17191
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=64128
ln __line__: __func__=redraw
ln __line__: path=/home/akrifari/Documents/oss/nnn
ln __line__: event->wd=1
ln __line__: event->mask=32768
ln __line__: "inotify read done"=inotify read done
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
ln __line__: event->wd=0
ln __line__: event->mask=0
ln __line__: "inotify read done"=inotify read done
```
</details>

To provide some context, this is what I have got from git bisect start from v3.5 to f602cbee0790bf9277dbc3623c90190012c5cea9. Hope it helps
<details>
<summary>git bisect log</summary>

```sh
 nnn (d07c490) git bisect log
git bisect start
# good: [f6cc2e616150737bdc0bd2f6dd390e2d2a15db32] Prepare for release v3.5 Freddie
git bisect good 5281f10c4655fbc0edf2923429b6dac9d1cd2bda
# bad: [f602cbee0790bf9277dbc3623c90190012c5cea9] Reorder table alphabetically
git bisect bad f602cbee0790bf9277dbc3623c90190012c5cea9
# bad: [e3c994bd369f6a037cc3343a1d4b9c679e9e7169] Merge pull request #852 from 0xACE/badideascfg
git bisect bad e3c994bd369f6a037cc3343a1d4b9c679e9e7169
# good: [fc3a247c317ca414eb5ec23bb24da6735cd91f77] Minor plugin indentation update
git bisect good fc3a247c317ca414eb5ec23bb24da6735cd91f77
# good: [f4baa394be2a719432b609768bff7d737e28b5ca] Merge pull request #836 from KlzXS/makefile
git bisect good f4baa394be2a719432b609768bff7d737e28b5ca
# good: [118657020e43fa75ab89bada281a7d9f25d69684] Fix indentation in helpstr
git bisect good 118657020e43fa75ab89bada281a7d9f25d69684
# bad: [026f76f14cdf6f67d29ed3cfd5804b2e2890bf6f] Clear selection after successful plugin invocation
git bisect bad 026f76f14cdf6f67d29ed3cfd5804b2e2890bf6f
# good: [8a12c01da41dcc238692c83bd393ebd42be9a9e4] fixed shellcheck errors for plugins/preview-tui
git bisect good 8a12c01da41dcc238692c83bd393ebd42be9a9e4
# good: [d07c4907de04a0200ffc43f20a0979b10f768894] Merge pull request #851 from Lucas-Summers/master
git bisect good d07c4907de04a0200ffc43f20a0979b10f768894
# first bad commit: [026f76f14cdf6f67d29ed3cfd5804b2e2890bf6f] Clear selection after successful plugin invocation
```
</details>

**Comment by amanjitsk** [comment] 2021-03-25 16:00
Same I had discovered this issue recently as well. 
I didn't really have a clean workaround this though, this is what I did
I replaced 
```
if [ "$resp" = "s" ]; then
    use_all
    sed -z 's|'"$PWD/"'||g' < "$selection" | xargs -0 "$dnd" "$all" &
```

with 

```
if [ "$resp" = "s" ]; then
    use_all
    # sed -z 's|'"$PWD/"'||g' < "$selection" | xargs -0 "$dnd" "$all" &
    if [ -z "$all" ]; then
      cat "$selection" | tr '\0' '\n' | sed -e '$a\' | "$dnd" -I
    else
      cat "$selection" | tr '\0' '\n' | sed -e '$a\' | "$dnd" "$all" -I
    fi
```
using the `--stdin/-I` flag for dragon. It has something to do with the non-blocking `&`, 
I think the shell interprets that as putting the `xargs` process in the background as opposed
to `$dnd`.

**Comment by jarun** [comment] 2021-03-25 19:48
We made a recent change to clear selection after invoking plugins if they do not send any data back to `nnn`,
To ensure there are no side effects, we need to check every plugin and see if it's doing anything with the selection after the plugin is exited.

I think to handle this we will add some logic in `nnn` to read back (and discard) dummy data from plugins which still need the selection to exist but doesn't really need to send any data back.

@0xACE would it be possible to do the analysis?

**Comment by jarun** [comment] 2021-03-26 14:13
@luukvbaal can you please help with this one?

**Comment by 0xACE** [comment] 2021-03-26 17:47
I'm away from home this weekend. I haven't had time to keep up with the merge conflicts of `master` and `private` so I never checked on these conflicts...

Best I can do is check out this topic next week...

**Comment by jarun** [comment] 2021-03-26 19:18
No hurry. Thank you!

**Comment by jarun** [comment] 2021-03-27 11:43
@akrifari please confirm if the issue is fixed now. You'll have to compile `nnn` and use it. The plugin remains unchanged.

**Closed** 2021-03-27 11:42 UTC
Labels: bug

**Comment by akrifari** [comment] 2021-03-27 14:32
@amanjitsk nice trick :+1: 

@jarun I can confirm it works as expected, thanks a lot!
