### ISSUE TITLE
Make preview-tui using kitty terminal splits close the split before opening text files to edit

### ISSUE THREAD

**Issue by David-Else** [jarun/nnn#1170] opened 2021-09-19 22:54 UTC
@luukvbaal Currently the preview is not closed and the split remains, is this a bug or a feature request? It seems like a bug, why keep the preview?

My `.bashrc` has:
```
alias nnn="nnn -xe"
export NNN_FIFO=/tmp/nnn.fifo

export EDITOR="nvim"
```
```
$ nnn -V
4.2
Source       : nnn-4.2-1.3.src.rpm
```

## select file with preview to the right
![Screenshot from 2021-09-19 23-41-23](https://user-images.githubusercontent.com/12832280/133945311-948c6e5b-58fb-475f-a692-e4baf874e4fe.png)
## open file (in Neovim) and preview remains
![Screenshot from 2021-09-19 23-41-32](https://user-images.githubusercontent.com/12832280/133945312-7a1f9c12-0e2d-4a3b-8288-d3d7c7562f95.png)

**Comment by luukvbaal** [comment] 2021-09-19 23:13
Not really a bug but I do agree it is unwanted behavior. The problem is that there is currently no way for `preview-tui` to know that a file was opened by `nnn`.

Would require something to be written to the FIFO when opening/editing a file.
Might be worthwhile addition. Currently the only two plugins that read from the FIFO are the preview plugins so it shouldn't be too much trouble.

What if we write some sort of opcode to the FIFO when opening/editing a file that can be checked in the preview plugins @jarun?

**Comment by luukvbaal** [comment] 2021-09-19 23:58
Like this I would say
```diff
diff --git a/plugins/preview-tui b/plugins/preview-tui
index b6788fc4..9f58e821 100755
--- a/plugins/preview-tui
+++ b/plugins/preview-tui
@@ -389,6 +389,7 @@ preview_fifo() {
         if [ -n "$selection" ]; then
             kill "$(cat "$PREVIEWPID")"
             [ -p "$FIFO_UEBERZUG" ] && ueberzug_remove
+            [ "$selection" = "open" ] && break
             preview_file "$selection"
             printf "%s" "$selection" > "$CURSEL"
         fi
diff --git a/src/nnn.c b/src/nnn.c
index 44f297f4..642edd04 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -846,7 +846,7 @@ static char *load_input(int fd, const char *path);
 static int set_sort_flags(int r);
 static void statusbar(char *path);
 #ifndef NOFIFO
-static void notify_fifo(bool force);
+static void notify_fifo(bool force, bool closepreview);
 #endif
 
 /* Functions */
@@ -3045,7 +3045,7 @@ try_quit:
 			} else {
 #ifndef NOFIFO
 				if (!g_state.fifomode)
-					notify_fifo(TRUE); /* Send hovered path to NNN_FIFO */
+					notify_fifo(TRUE, FALSE); /* Send hovered path to NNN_FIFO */
 #endif
 				escaped = TRUE;
 				settimeout();
@@ -5787,7 +5787,7 @@ static void populate(char *path, char *lastname)
 }
 
 #ifndef NOFIFO
-static void notify_fifo(bool force)
+static void notify_fifo(bool force, bool closepreview)
 {
 	if (!fifopath)
 		return;
@@ -5803,6 +5803,11 @@ static void notify_fifo(bool force)
 		}
 	}
 
+  if (closepreview) {
+	  write(fifofd, "open\n", 6);
+    return;
+  }
+
 	static struct entry lastentry;
 
 	if (!force && !memcmp(&lastentry, &pdents[cur], sizeof(struct entry)))
@@ -5852,7 +5857,7 @@ static void move_cursor(int target, int ignore_scrolloff)
 
 #ifndef NOFIFO
 	if (!g_state.fifomode)
-		notify_fifo(FALSE); /* Send hovered path to NNN_FIFO */
+		notify_fifo(FALSE, FALSE); /* Send hovered path to NNN_FIFO */
 #endif
 }
 
@@ -6735,7 +6740,7 @@ nochange:
 					move_cursor(r, 1);
 #ifndef NOFIFO
 				else if ((event.bstate == BUTTON1_PRESSED) && !g_state.fifomode)
-					notify_fifo(TRUE); /* Send clicked path to NNN_FIFO */
+					notify_fifo(TRUE, FALSE); /* Send clicked path to NNN_FIFO */
 #endif
 				/* Handle right click selection */
 				if (event.bstate == BUTTON3_PRESSED) {
@@ -6808,7 +6813,7 @@ nochange:
                         }
 #ifndef NOFIFO
 			if (g_state.fifomode && (sel == SEL_OPEN)) {
-				notify_fifo(TRUE); /* Send opened path to NNN_FIFO */
+				notify_fifo(TRUE, FALSE); /* Send opened path to NNN_FIFO */
 				goto nochange;
 			}
 #endif
@@ -6943,6 +6948,7 @@ nochange:
 
 			/* Invoke desktop opener as last resort */
 			spawn(opener, newpath, NULL, NULL, opener_flags);
+      notify_fifo(FALSE, TRUE);
 
 			/* Move cursor to the next entry if not the last entry */
 			if (g_state.autonext && cur != ndents - 1)
@@ -7198,6 +7204,7 @@ nochange:
 				copycurname();
 				goto nochange;
 			case SEL_EDIT:
+        notify_fifo(FALSE, TRUE);
 				spawn(editor, newpath, NULL, NULL, F_CLI);
 				continue;
 			default: /* SEL_LOCK */
@@ -8681,7 +8688,7 @@ int main(int argc, char *argv[])
 
 #ifndef NOFIFO
 	if (!g_state.fifomode)
-		notify_fifo(FALSE);
+		notify_fifo(FALSE, FALSE);
 	if (fifofd != -1)
 		close(fifofd);
 #endif
```

**Comment by David-Else** [comment] 2021-09-20 08:44
I would hope it would only close the preview if it were opening a text file in the same terminal `nnn` was running (as in the image I posted). If you open a file in a separate program, like a pdf or image viewer, the preview should stay. Do you agree?

**Comment by luukvbaal** [comment] 2021-09-20 09:25
Yeah I guess that makes sense, just waiting for @jarun.
If he's okay with a change like this we can open a PR for the specific implementation.

**Comment by luukvbaal** [comment] 2021-09-20 14:01
> If you open a file in a separate program, like a pdf or image viewer, the preview should stay. Do you agree?

On the other hand, for `preview-tabbed` it probably makes more sense to close the previewer regardless of whether it is opened detached or internally.

I think for `preview-tui` this behavior should also be fine; once you open a file you don't need the preview anymore right? You can always re-open when you get back to `nnn`.

**Comment by luukvbaal** [comment] 2021-09-20 14:16
Went ahead and made the PR #1171 for clarity.

**Comment by David-Else** [comment] 2021-09-20 16:00
> I think for preview-tui this behaviour should also be fine; once you open a file you don't need the preview anymore right?

I see no reason to turn the preview off unless it prevents opening a file in the terminal full screen as in my example. I personally like the preview on all the time and would find it annoying to have to keep on turning it on again after opening a file. I keep an instance off `nnn` open all the time in a terminal tab (with preview on) and use it to look around my hard drive and open and edit files.

There seems two types of file, those opened right there in the terminal that you would expect to have the full screen and no more preview, and those that open in a separate program that is not the terminal (like pdf, images, music and video). I would expect only the former to turn off the preview.

**Comment by Kabouik** [comment] 2021-09-20 19:44
Would be nice if the preview could be turned back on when closing the text file. I assume it can be done with FIFO too?

**Comment by jarun** [comment] 2021-09-21 04:58
@luukvbaal please take a call on this thread when you are through discussions.

**Comment by luukvbaal** [comment] 2021-09-21 14:52
> @luukvbaal please take a call on this thread when you are through discussions.

Was hoping for some feedback from you on whether this change would be welcome but I made a PR with what I thought was necessary to implement this.

**Comment by jarun** [comment] 2021-09-21 15:16
I am just too busy nowadays.

Thanks a lot for the PR. However, I see it's too much change for minor inconvenience. Let's drop this.

**Closed by jarun** 2021-09-21 15:16 UTC
Labels: enhancement
