### ISSUE TITLE
nnn -b key not working. 

### ISSUE THREAD

**Issue by philFernandez** [jarun/nnn#229] opened 2019-03-20 18:06 UTC
The nnn -b key feature is not working at all for me. I have several bookmarks defined with the environment variable NNN_BMS, and none of them will open via the command nnn -b key. I just get a message saying 'invalid key'. 

I'm on Mac OS 10.14, using ZSH 5.3

**Comment by jarun** [comment] 2019-03-20 18:14
Looks like a regression in the latest release. I can reproduce it. Checking...

**Comment by jarun** [comment] 2019-03-20 18:23
This should be fixed on master now. Thanks for the bug report! :+1:

**Closed** 2019-03-20 18:22 UTC
