### ISSUE TITLE
Segfault when setting plugin

### ISSUE THREAD

**Issue by siraben** [jarun/nnn#766] opened 2020-10-21 15:49 UTC
I was trying to set a plugin to page the current file using less, however it segfaults when I trigger it with `;p`

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: macOS
- [ ] Desktop Environment:
- [x] Terminal Emulator: kitty
- [x] Shell: zsh
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
```
NNN_PLUG='p:-_less -iR $nnn*;l:-_git log' nnn
```

**Comment by 0xACE** [comment] 2020-10-21 16:45
Checked out `master` just for you:

Cannot replicate the error.

Nor can I replicate the error with my personal branch.

run `make debug && gdb nnn` and give us a `bt full` when you hit the segfault

**Comment by jarun** [comment] 2020-10-21 17:43
I can't reproduce this on master either.

Please provide the following details as well:

- which other `NNN_` config have you set?
- From the help screen copy and share everything from `PLUGIN_KEYS` line to the end.

**Comment by siraben** [comment] 2020-10-22 08:35
Looks like my [home-manager](https://github.com/nix-community/home-manager) config expanded the bash variable, so inspecting the value of `NNN_PLUG` I get the following;
```bash
$ echo $NNN_PLUG                              
'p:-_less -iR *;l:-_git log'
```

**Comment by KlzXS** [comment] 2020-10-22 08:59
No, I still can't get it to segfault. `less` just fails to with `Missing filename ("less --help" for help)`, which I would expect.
But I don't have macOS, maybe it's related to being mac?

But do give as a stack trace as @0xACE suggested.

**Comment by jarun** [comment] 2020-10-22 09:15
@siraben 

In my system:

```
// with single quotes
$ export NNN_PLUG='p:-_less -iR $nnn*;l:-_git log'                                            
$ echo $NNN_PLUG                                  
p:-_less -iR $nnn*;l:-_git log

// with double quotes
$ export NNN_PLUG="p:-_less -iR $nnn*;l:-_git log"
$ echo $NNN_PLUG                                  
p:-_less -iR *;l:-_git log // $nnn is gone!
```

I think you are using double quotes around the alias and that's the problem.

Do you really want the the `$nnn` to be gone? Otherwise please fix that. I think that is causing the problem. Please ensure the removal doesn't happen.

I am closing this as a local environment problem. Please get back if fixing the above doesn't fix your problem. We will reopen the issue.

**Closed by jarun** 2020-10-22 09:15 UTC
Labels: bug

**Comment by jarun** [comment] 2020-10-22 09:16
Please ensure the `$nnn` is not removed whatever may be the reason. Because that's an invalid input.

**Comment by siraben** [comment] 2020-10-27 05:44
I tried `NNN_PLUG='p:-_less -iR $nnn*;l:-_git log' nnn`, and it segfaults when invoking the `p` plugin key.

**Comment by jarun** [comment] 2020-10-27 05:56
In that case, please provide all the details requested earlier.

**Comment by jarun** [comment] 2020-10-27 05:58
Also, what is your version of nnn? Is this happening on master?

**Comment by siraben** [comment] 2020-10-27 06:03
Side note; after segfault it seems to mess up how my terminal receives control characters as well.

> Also, what is your version of nnn? Is this happening on master?

My version of nnn is 3.4. I just tried it on master and got the same result.

> which other NNN_ config have you set?

No other config set.

**Comment by jarun** [comment] 2020-10-27 06:18
Mess-up is expected after ncurses faulty exit. Please provide the details @0xACE and I requested in the first 2 responses.

**Comment by siraben** [comment] 2020-10-27 06:19
My `gdb` isn't properly configured on darwin, so I'll see what happens on Linux and provide a backtrace.

**Comment by jarun** [comment] 2020-10-27 16:22
I just tried it on a macOS shell using [fastmac](https://github.com/jarun/fastmac) and the files open as expected in `less` when I press `Alt-P` or `;P`.

It's Darwin and brew installed nnn v3.4:

```
$ uname -a
Darwin Mac-1603815181651.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-
6153.141.2~1/RELEASE_X86_64 x86_64
```

Please confirm if your less is aliased to something? Try `which less`. For me it's `/usr/bin/less`.

**Comment by siraben** [comment] 2020-10-27 17:07
`which less` gives `/usr/bin/less` for me

**Comment by jarun** [comment] 2020-10-27 17:12
Can you share the details under `PLUGIN KEYS` in help screen?

**Comment by 0xACE** [comment] 2020-10-27 18:10
> My `gdb` isn't properly configured on darwin, so I'll see what happens on Linux and provide a backtrace.

Seems like they have `lldb`, could you generate a backtrace from:
1. `make debug && lldb ./nnn`
2. start it by typing `run` in `lldb`
2. reproduce the segfault
3. `bt` (or if they have a equivalent to `bt full`

This could be helpful
https://lldb.llvm.org/use/map.html

**Comment by siraben** [comment] 2020-10-28 04:03
> Can you share the details under `PLUGIN KEYS` in help screen?

How do I do this?

**Comment by siraben** [comment] 2020-10-28 04:04
Looks like the segfault also occurs when running the other plugin (git log) with `;l`.

**Comment by siraben** [comment] 2020-10-28 04:06
I can't select the text so here is a screenshot of `lldb`
<img width="772" alt="nnn segfault" src="https://user-images.githubusercontent.com/8219659/97389696-e048d380-18d2-11eb-8048-3a69622b46e9.png">

**Comment by jarun** [comment] 2020-10-28 04:40
Please provide the full backtrace however you can.

**Comment by siraben** [comment] 2020-10-28 04:43
That seems to be the full backtrace.

**Comment by 0xACE** [comment] 2020-10-28 04:53
@siraben, we would need the variables in `frame #3`. I'm not familiar with `lldb` but you need to print out the local variables in that frame. and potentially `frame #2` could be interesting. maybe `frame 3` and `fr v` should yield some results. im going to bed, seems like jarun is around at least. good night

**Comment by jarun** [comment] 2020-10-28 10:39
@siraben I think you may not have compiled nnn in debug mode: https://github.com/jarun/nnn/wiki/Developer-guides#debugging-nnn

**Comment by jarun** [comment] 2020-10-28 10:40
Also, run `bt full`

**Comment by jarun** [comment] 2020-11-19 14:18
@siraben this is fixed at #786.

**Comment by siraben** [comment] 2020-11-19 14:30
Ah, looks like the way to get the backtrace was `bt all`.

I just rebuilt it with Nix, and confirm that the issue is resolved.

**Comment by jarun** [comment] 2020-11-19 14:31
Thanks for the confirmation!
