### ISSUE TITLE
Error with generating nnn preview tui encoding

### ISSUE THREAD

**Issue by awelormro** [jarun/nnn#1688] opened 2023-07-11 01:50 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [ ] Operating System:
- [ ] Desktop Environment:
- [ ] Terminal Emulator:
- [ ] Shell:
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used: compiled via source code with nerdfonts for custom icons
- [ ] Configuration options set:
- [ x ] Plugins are installed: Preview tui plugin, tree, less, bat installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

Installed via source code, everything works as expected with nnn, but when I tried to install the preview-tui plugin, it just does not apply the correct color schemas nor visualize images, the compilation was the nerdfonts way to add custom icons for some filetypes, everything works as expected, tested in tmux with urxvt, alacritty and the error comes when it is invoked inside a tmux session, it is unable to reproduce the colors, as an encoding error, when it is opened in a single terminal window, without tmux, it runs correctly, but has errors with a tmux instance. Thanks four building this awesome tool!

**Comment by dualfade** [comment] 2023-07-12 03:02
same issue here. This was working fine until not too long ago here.

**Comment by N-R-K** [comment] 2023-07-20 20:24
So it looks like this was a ueberzug bug and not a bug in preview-tui (?)

Closing. Let me know if that's not the case.

**Closed by N-R-K** 2023-07-20 20:24 UTC
Labels: bug
