### ISSUE TITLE
sshfs mountpoint other then home

### ISSUE THREAD

**Issue by microo8** [jarun/nnn#684] opened 2020-07-21 10:53 UTC
**Is your feature request related to a problem? Please describe.**

I want to mount to remote folder other than home directory. Ideal would be root, so that I can browse all files on the remote server.

**Describe the solution you'd like**

something like adding a path to the remote name. pressing 'c', then type remote name with the path (`remotename:/var/www`)

**Describe alternatives you've considered**

is there a way to set the path to sshfs for the specific remote?

**Comment by jarun** [comment] 2020-07-21 11:16
I think you can configure the destination path in ssh config file.

**Comment by 0xACE** [comment] 2020-07-21 12:03
I couldn't find the config variable for that in `SSH_CONFIG(5)` so I'll provide a patch instead.

```
diff --git a/src/nnn.c b/src/nnn.c
index c5ab000..49c1449 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -4033,8 +4033,7 @@ static bool remote_mount(char *newpath)
 	size_t len = xstrlen(tmp);
 
 	if (tmp[len - 1] != ':') { /* Append ':' if missing */
-		tmp[len] = ':';
-		tmp[len + 1] = '\0';
+		xstrsncpy(&tmp[len], ":/", 3);
 	}
 
 	/* Connect to remote */
```

**Comment by jarun** [comment] 2020-07-21 12:07
Also, there's `LocalCommand`.

**Comment by jarun** [comment] 2020-07-21 12:25
Closing with the patch. No plans to prolong the workflow with an additional question.

**Closed by jarun** 2020-07-21 12:25 UTC
Labels: enhancement

**Comment by jarun** [comment] 2020-07-21 12:26
If it helps, there's also `NNN_SSHFS`.

**Comment by Kabouik** [comment] 2020-07-21 12:38
> I think you can configure the destination path in ssh config file.

I can confirm this is what I'm using:

```
Host Pro2
    HostName 192.168.1.38
    User nemo
    Port 22
    IdentityFile ~/.ssh/id_rsa
    Compression no
    #Ciphers chacha20-poly1305@openssh.com

Host Pro2r
    HostName 192.168.1.38
    User root
    Port 22
    IdentityFile ~/.ssh/id_rsa
    Compression no
    #Ciphers chacha20-poly1305@openssh.com
```

**Comment by microo8** [comment] 2020-07-22 06:48
This patch only mounts the root every time.
I was hoping, that I will be able to set the path if I wan to
like `remotename:/whatever/path/i/want`

@Kabouik where exactly is the mount path in that ssh config?

Can this be added to the TODO list and I make that optional path passing in a pull request? That would be ok?

**Comment by Kabouik** [comment] 2020-07-22 07:30
Actually you're right, I answered too fast, I just mount *as* root or *as* user in this config, but this doesn't necessarily alter the path (although it obviously allows me to browse and write in locations where the normal users has no permissions). Sorry for the confusion.

**Comment by jarun** [comment] 2020-07-22 08:00
@microo8 please feel free to raise the PR!

**Comment by jarun** [comment] 2020-07-22 11:32
@microo8 can you please confirm the patch for both ssh and rclone? (you can use the same remote)

**Comment by jarun** [comment] 2020-07-22 11:55
I think I mixed this up with `scp`. This wouldn't work.

Not sure if it's even possible with ssh: https://superuser.com/questions/250533/how-to-ssh-to-the-remote-path

**Comment by jarun** [comment] 2020-07-22 11:56
Ignore my earlier comment. Deleted.

**Comment by jarun** [comment] 2020-07-22 11:56
Please test the patch and confirm it works as expected for SSHFS and rclone.

**Comment by leovilok** [comment] 2020-07-22 12:30
With sshfs mounting works, but not unmounting.

**Comment by leovilok** [comment] 2020-07-22 12:31
maybe because the mountpoint directory is `host:` instead of `host`

**Comment by jarun** [comment] 2020-07-22 12:43
I have fixed that in commit 32ec37a796d2c5934250bcd6b6dbbeb0c5133ce3. Please re-test.

**Comment by microo8** [comment] 2020-07-22 12:49
Wow that was fast, it works! Thanks

**Comment by jarun** [comment] 2020-07-22 13:02
@leovilok @microo8 Please confirm that unmounting works fine for you.

**Comment by leovilok** [comment] 2020-07-22 14:22
Unmounting works now.

**Comment by jarun** [comment] 2020-07-22 14:50
Cool!
