### ISSUE TITLE
Filepicker ffnnn wrapper script in documentation does not work for multiple selected files

### ISSUE THREAD

**Issue by Carlisle96** [jarun/nnn#1466] opened 2022-08-22 17:00 UTC
Thank you for the amazing help with me previous request. I have everything setup correctly and working now.
- [X] Operating System: Fedora
- [X] Desktop Environment: XMonad
- [X] Terminal Emulator: Kitty
- [X] Shell: Zsh
- [ ] Custom desktop opener (if applicable):
- [X] Program options used: -p ( fffnnn wrapper script )
- [ ] Configuration options set:
- [X] Plugins are installed
- [X] Issue exists on `nnn` master

I have file selection working now with xdg-desktop-portal on all applications. However only single files and directories seem to work. 
Selecting multiple files at once doesn't seem to work. It only passes on the first selected file.

running nnn -p - on the command line does indeed print all the selected files so it seems that the problem lies in the wrapper script fffnnn.

**Comment by luukvbaal** [comment] 2022-08-22 17:14
Cannot reproduce, what are you trying to do?
I tried uploading multiple files to zippyshare.com which works fine.

**Comment by Carlisle96** [comment] 2022-08-22 18:19
I checked selecting multiple files with sublime and https://viljamis.com/filetest/, I cannot test Zippyshare ( error 403 )
I checked another site for work I know accepts multiple files and it also only selects the first. 
Are you using the same fffnnn wrapper ?

**Comment by Carlisle96** [comment] 2022-08-23 00:56
I can provide additional information:
A trace from the log of the termfilechoser shows some strange resutls: https://termbin.com/dula
at the same time /tmp/termfilechooser.portal shows indeed 2 files correctly written

It only reads the first file in the list, because Number of selected files seemts to be 1

**Comment by Carlisle96** [comment] 2022-08-23 02:10
Deleting line 58 in https://github.com/GermainZ/xdg-desktop-portal-termfilechooser/blob/main/src/filechooser/filechooser.c fixes the problem.
Which version of termfilechooser are you using ? I think it can't work, due to an error in the code - if you couldn't reproduce the issue - what termfilechooser version did you use ?

**Comment by luukvbaal** [comment] 2022-08-24 08:54
> Are you using the same fffnnn wrapper ?

Yes, same version as listed on the wiki.

> Which version of termfilechooser are you using ?

Latest version built from git (through AUR). I've only tested this through firefox, can't speak for other programs. Closing because not an issue with nnn, feel free to discuss further though.

**Closed by luukvbaal** 2022-08-24 08:54 UTC
Labels: bug

**Comment by Carlisle96** [comment] 2022-08-24 11:57
Yes. I think the issue is with termfilechooser, due to a bug in the code. I have everything working now with a modified termfilechooser. I will submit a pullrequest to termfilechooser.

**Comment by amalgame21** [comment] 2022-08-24 12:53
> Deleting line 58 in https://github.com/GermainZ/xdg-desktop-portal-termfilechooser/blob/main/src/filechooser/filechooser.c fixes the problem. Which version of termfilechooser are you using ? I think it can't work, due to an error in the code - if you couldn't reproduce the issue - what termfilechooser version did you use ?

This also solve the problem for me. Thanks!
Add a patch in PKGBUILD in AUR  to delete line 58, and it works fine now.

**Comment by N-R-K** [comment] 2022-08-24 17:44
@Carlisle96 I think this PR should fix your issue? https://github.com/GermainZ/xdg-desktop-portal-termfilechooser/pull/2/files

NGL, just glancing at it there's a lot of other problems with that codebase...

**Comment by Carlisle96** [comment] 2022-08-26 11:01
@N-R-K Yea, I don't really know how to fix it. I know my way around C but not for writing a solid, production level application. But it would be good if there is a overhaul in the code. That PR would fix the issue. I think moving it to line 57 is not neccesary - better just delete it.

There are also other issues, uncertain behavior on cancel and usage of the reccomended file and it opens an empty file when aborting. I don't know how to address all these issues properly.
