### ISSUE TITLE
Unmount remote: change default from "hovered" to "hovered or parent"

### ISSUE THREAD

**Issue by Kabouik** [jarun/nnn#854] opened 2021-02-12 14:56 UTC
Currently when pressing `u` to unmount a remote folder, the user can write the name of the remote or unmount the hovered folder (which is default). Given that nnn is often built around optimizing the number of key presses for many actions, would it make sense to default to unmounting not only hovered folder, but any remote parent to the currently hovered folder? 

For instance, say I mount `pro` into `~/.config/nnn/mounts/pro`, then use this remote to browse some files in `~/.config/nnn/mounts/pro/home/pro/Pictures/Screenshots`, I would want to unmount it once I'm done, and I see only situations were it would be more straightforward to directly unmount with `u` then `return` while I'm in this child folder instead of browsing back to `~/.config/nnn/mounts/pro` or typing "pro". Am I missing some other situations where this would be an inconvenience?

**Comment by 0xACE** [comment] 2021-02-12 20:38
I agree... but i do this instead (unmount all my mounts, trigger it when im finished with everything)
```
err=0
for d in ~/.config/nnn/mounts/*/; do
    mountpoint -q -- "$d"
    if [ "$?" -eq "0" ]; then
        fusermount3 -u "$d" || err=1
    fi
done

[ "$err" -eq "1" ] && read -n 1 -s -r -p "Failed to unmount. Press any key to continue"

exit 0
```

Feel free to fix the script, it may be incredibly broken...

**Comment by Kabouik** [comment] 2021-02-12 21:00
Interesting, thanks 0xACE. There are cases where unmounting all remotes at the same time could be inconvenient forme. Typically I would mount my phone temporarily to copy some pictures or documents, which is completely unrelated to the other remotes I may mount.

Surely I could leave my phone mounted, but as was discussed some months ago in another issue, I'm not comfortable with keeping wireless devices mounted in in a `~/.config/nnn` subfolder when not in use, I would likely forget about them eventually, and possibly break things badly when trying to stash or git pull in my `nnn` folder at a later point.

**Comment by 0xACE** [comment] 2021-02-12 21:54
Yeah I agree, thats why I wish `u` would also unmount if you are in a sub-directory of a mounted directory... Alas I'm lazy and went with the script that unmounts them all (and honestly i forget to unmount them more often than you think). you could very easily re-adjust the script to do what you like... but really I'm hoping for that it your feature request gets accepted, as it makes sense to me that it should unmount the parent if it's a `nnn` mount...

I would rather focus my remaining energy on getting a "nicer" `mv`/`cp` progress bar integrated into `nnn` than relying on `mvg`/`cpg`, but I have other responsibilities atm...

**Comment by Kabouik** [comment] 2021-02-12 22:26
I suppose it should be possible to get the parent mount of the current directory in bash using things like (1) `$PWD`, (2) hardcoded `nnn` mount folder with its subfolders (since I don't think there's any way to change the mount dir with environment variables, that's what we discussed in this other issue I mentioned), and (3) some regex magic to find which of nnn's mount subfolders is used at the highest level of (1).

I don't know anything about regex but I'll try to do some research.

**Comment by Kabouik** [comment] 2021-02-12 23:44
Maybe this:

```
echo "$PWD" | grep -oP "^$HOME/.config/nnn/mounts\K.*" | cut -d"/" -f2
```

Not sure how to include that in a script or directly in nnn yet, I still have to test some situations to make sure there are no corner cases where it would return something incorrect.

**Comment by 0xACE** [comment] 2021-02-13 00:19
I'm glad i looked up `\K` wasn't familiar with it, nice find.

Easiest would be `Alt-u` (same as `;u`, `alt` lets you trigger scripts). For w/e reason I recall that you ought to first check that the target directory is a mounted directory, I think that's the `mountpoint` part of the script i provided...

**Comment by jarun** [comment] 2021-02-27 18:21
Please let me know if we can close this thread.

**Comment by Kabouik** [comment] 2021-02-27 19:53
I haven't figured out how to make a script for this yet (but to be honest I didn't have the opportunity to spend any time on it so far), but I think you can close it if it is not included in nnn anyway. If I ever come up with a script I'll update this issue even if it's closed.

**Comment by jarun** [comment] 2021-02-28 02:25
Thanks for the confirmation!

**Closed by jarun** 2021-02-28 02:25 UTC
Labels: enhancement

**Comment by Kabouik** [comment] 2021-04-28 01:04
When unmounting a folder with `u` in nnn and it fails, nnn offers to try lazy loading. How does that work exactly? I know `umount -l example` but it requires `sudo`.

I think I progressed towards a small script to do the thing discussed above with:

```bash
#!/usr/bin/env sh

# Description: unmount nnn mountpoints from any of their child folders
# (vanilla `u` in nnn requires either to go back to the parent folder or to enter the mount name)
# Author: Kabouik & 0xACE

m=$HOME/.config/nnn/mounts
d=$(echo "$PWD" | grep -oP "^$m\K.*" | cut -d"/" -f2)

err=0
    if mountpoint -- "$m/$d" | grep "is a mountpoint" > /dev/null; then
        fusermount3 -u "$d" || err=1
    else
        echo "Parent '$d' is not a mountpoint."
    fi

[ "$err" -eq "1" ] && read -n 1 -s -r -p "Failed to unmount. Press any key to continue."
```

but `fusermount -u` fails because my mounted folder (a phone mounted with sshfs) busy due to nnn itself, so I would need to include another method when that happens:

```
$ lsof +f -- /home/mathieu/.config/nnn/mounts/Pro2
COMMAND    PID    USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
nnn     822963 kabouik  cwd    DIR   0,55     4096   40 /home/mathieu/.config/nnn/mounts/Pro2/.cache
nnn     823322 kabouik  cwd    DIR   0,55     4096   40 /home/mathieu/.config/nnn/mounts/Pro2/.cache
sh      823323 kabouik  cwd    DIR   0,55     4096   40 /home/mathieu/.config/nnn/mounts/Pro2/.cache
```

**Comment by 0xACE** [comment] 2021-04-28 10:11
>nnn offers to try lazy loading. How does that work exactly?

Can't comment on it as I don't have the code infront of me. Look at the source, `nnn.c` source is rather easy to navigate... look for `SEL_UMOUNT` or w/e it's called

> but `fusermount -u` fails because my mounted folder (a phone mounted with sshfs) is busy due to nnn itself, so I would need to include another method when that happens:

That is by design for busy resources... `man fusermount` mentions `-z` for lazy, and `man umount` mentions:

```
       -l, --lazy
              Lazy  unmount.   Detach the filesystem from the file hierarchy now, and clean up all references to this filesystem
              as soon as it is not busy anymore.

              A system reboot would be expected in near future if you're going to use this option for network filesystem or  lo‐
              cal  filesystem  with submounts.  The recommended use-case for umount -l is to prevent hangs on shutdown due to an
              unreachable network share where a normal umount will hang due to a downed server or a network partition.  Remounts
              of the share will not be possible.
```

Do with it what you please, but be vary of potential issues.

In my personal use case, i just unmount after everyone else are done with it. and on failure, reveals the error before returning to `nnn`

> I know `umount -l example` but it requires `sudo`.

you can add a `/usr/local/sbin/snnn_unmount` (ensure its only writable by `root`) which unmounts anything under `$XDG_CONFIG/nnn/mounts` and add it to a passworld less `sudo` command in `visudo`. then you can launch it as `sudo snnn_umount` without a password prompt... I'm only mentioning this in hope that you learn something from this. Peace

**Comment by Kabouik** [comment] 2021-04-28 10:34
Alright, thanks a lot @0xACE. 

I think this should work:

```
#!/usr/bin/env sh

# Description: unmount a nnn mountpoint from any of its subfolders (vanilla `u` in nnn requires either
# going back to ~/.config/nnn/mounts to hover the mountpoint, or to enter its name in the `u` prompt)
# Author: Kabouik & 0xACE

m=$HOME/.config/nnn/mounts
d=$(echo "$PWD" | grep -oP "^$m\K.*" | cut -d"/" -f2)
err=0

    mountpoint -q -- "$m/$d"
    if [[ $? -eq "0" ]]
    then
        fusermount -u "$m/$d" && rmdir "$m/$d" && echo "Parent '$d' unmounted." || err=1
    else
        read -n 1 -s -r -p "Parent '$d' is not a mountpoint. Press any key to continue."
    fi

    [[ $err -eq "1" ]] && read -n 1 -s -r -p "Failed to unmount. Try lazy unmount? Yy/Nn"
        echo # Move to a new line
        if [[ $REPLY =~ ^[Yy]$ ]]
        then
            fusermount -uz "$m/$d" && rmdir "$m/$d" && echo "Parent '$d' unmounted with lazy unmount."
        fi
```

Pleast let me know if it´s worth a PR.

**Comment by Kabouik** [comment] 2021-04-28 23:10
### Short update

[![asciicast](https://asciinema.org/a/410580.svg)](https://asciinema.org/a/410580)

This cast shows the script in action:
1. When invoked from outside of `~/.config/nnn/mounts`, operation is aborted because the script is only meant to deal with resources mounted with nnn `c` command.
2. When invoked while hovering a directory in `~/.config/nnn/mounts` but that is not a mountpoint, operation is aborted.
3. When invoked from a subfolder of the above folder, the correct parent is recognized, but operation is aborted if it is not a mountpoint.
4. When invoked from a subfolder of an actual mountpoint, the shell `cd ~/.config/nnn/mounts` to try not to keep the mountpoint busy, and so does the current nnn context. However, two issues: (1) that does not seem to be enough, maybe I need a `sleep`, and (2) the command used to change the active directory in the context breaks the nnn UI because the prompt to offer lazy unmount as a workaround for a busy resource shows on top of the nnn UI. See 00'29". Answering `y` or `Y` to the prompt would try lazy unmount and would work, but the UI stays broken.
5. When invoked while hovering the parent mountpoint in `~/.config/nnn/mounts`, it is correctly unmounted (but UI was already broken by the previous case in the cast).

I have identified that the part of the script that breaks the nnn UI by overlapping a prompt on top of the UI is `printf "%s" "0c$m" > "$NNN_PIPE"`. The same happens if I use `nnn_cd "$m" 0` instead after sourcing `.nnn-plugin-helper`.

Has there been other reports of UI breaking when changing the context active directory from a script? At this point I don't really understand what is wrong. The script works if I run it directly in terminal without nnn (with required changes to environment variables of course).

```bash
#!/usr/bin/env sh

# Description: unmount a nnn mountpoint from any of its subfolders (vanilla `u` in nnn requires either
# going back to ~/.config/nnn/mounts to hover the mountpoint, or to enter its name in the `u` prompt)
# Authors: Kabouik & 0xACE

# Environment
err=0
m=$HOME/.config/nnn/mounts
if [ "$PWD" = "$m" ] # Allow using the script on hovered directory if user is in ~/.config/nnn/mounts
then
    d="$1"
else
    d=$(echo $(dirname $(readlink -f "$1")) | grep -oP "^$m\K.*" | cut -d"/" -f2)
fi

# Test if user is currently within $m or a subfolder, abort if not
    if [ "$d" = "" ]
    then
        read -n 1 -s -r -p "You are not in folder mounted with nnn. Press any key to continue."
        clear
    else
        # Test if $m/$d is a mountpoint and try unmounting if yes
        mountpoint -q -- "$m/$d"
        if [ "$?" -eq "1" ]
        then
            read -n 1 -s -r -p "Parent '$d' is not a mountpoint. Press any key to continue."
            clear
        else
            cd "$m" && printf "%s" "0c$m" > "$NNN_PIPE"
            fusermount -uq "$m/$d" || err=1
            if [ "$err" -eq "0" ]
            then
                rmdir "$m/$d" && printf "Parent '$d' unmounted."
                clear
            fi
        fi
    fi

# If failure to unmount, offer to try lazy unmount
    if [ "$err" -eq "1" ]
    then
        read -n 1 -s -r -p "Failed to unmount. Try lazy unmount? Yy/Nn"
    fi

    if [ "$REPLY" = "y" -o "$REPLY" = "Y" ]
    then 
        cd "$m" && printf "%s" "0c$m" > "$NNN_PIPE"
        err=0
        fusermount -uqz "$m/$d" || err=1
        if [ "$err" -eq "0" ]
        then
            rmdir "$m/$d" && printf "Parent '$d' unmounted with lazy unmount."
            clear
        fi
    fi
```
