### ISSUE TITLE
Broken window on closing `preview-tui-ext` after navigating to parent dir

### ISSUE THREAD

**Issue by jarun** [jarun/nnn#998] opened 2021-05-11 17:15 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04 x86_64
- [x] Desktop Environment: XFCE4
- [x] Terminal Emulator: xfce4-terminal
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: `-acdDEnQrux`
- [x] Configuration options set: `NNN_PLUG`
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

I am seeing an issue with `preview-tui-ext` with [netbsd-curses and musl libc compilation](https://github.com/jarun/nnn/blob/master/misc/musl/musl-static-ubuntu.sh).

Compilation commands used:

```
$ musl-gcc -O3 -DNORL -DNOMOUSE -DNOBATCH -DTOURBIN_QSORT -DNOSSN -DNOUG -DNOX11 -march=corei7 -I../netbsd-curses/libcurses -o nnn src/nnn.c -Wl,-Bsymbolic-functions -L/opt/netbsd-curses -lcurses -lterminfo -static
$ strip nnn
```

Plugins are from latest master.

I have set it as `p:-preview-tui-ext` in `NNN_PLUG`. I use `tmux tmux 3.0a` with the config:

```
# remap prefix from 'C-b' to 'C-\'
unbind C-b 
set-option -g prefix C-c 
bind-key C-c send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"' 
unbind %

set -g escape-time 0
set-option -g status off

set -g default-terminal "xterm-256color"
```

I can repro this with:

- run the plugin with <kbd>Alt-P</kbd>
- move up a directory
- close the plugin with <kbd>Alt-P</kbd>
- window is broken with the following message: `dir changed, range sel off`

[![Asciicast](https://asciinema.org/a/aFhBcmqYRR99BvOtTR5AMvUy5.svg)](https://asciinema.org/a/aFhBcmqYRR99BvOtTR5AMvUy5)

**Comment by jarun** [comment] 2021-05-11 23:47
Adding @leovilok.

@luukvbaal Does the message `dir changed, range sel off` give some ideas? `MSG_DIR_CHANGED` is used at only one place in `nnn.c`. It looks like somehow the program has entered the `SEL_SELMUL` case.

**Comment by luukvbaal** [comment] 2021-05-11 23:51
Well the only I can see that happening is if `preview-tui-ext` somehow passes key presses to `nnn` right?

**Comment by jarun** [comment] 2021-05-11 23:53
Yes, possible. I just tested with `preview-tabbed` and I don't see this problem.

Also note that I am pressing <kbd>Alt-P</kbd> to close the previewer.

**Comment by luukvbaal** [comment] 2021-05-12 00:00
> Also note that I am pressing Alt-P to close the previewer.

Yeah I am too, couldn't reproduce yet. 

BTW `netbsd-curses` doesn't seem to play nice with `st`(suckless` simple terminal). When toggling  preview-tui I see flickering of the trailing whitespace in `nnn`. Doesn't happen when just opening/closing `tmux` panes though🤔

**Comment by jarun** [comment] 2021-05-12 00:05
Does `preview-tui(-ext)` write something back to `nnn` when it's closed with the same plugin key?

**Comment by luukvbaal** [comment] 2021-05-12 00:13
> Does `preview-tui(-ext)` write something back to `nnn` when it's closed with the same plugin key?

If it does it's not intended. Toggling is done by killing the `cat "$NNN_FIFO"` pipe.


Could you try 
```diff
@@ -430,6 +430,6 @@ else
         printf "\$KITTY_LISTEN_ON not set!\nPlease read Usage in preview-tui-ext."
         cfg=$(stty -g); stty raw -echo; head -c 1; stty "$cfg"
     else
-        togglepreview "$1" &
+        togglepreview "$1" > "`~/test &
     fi
 fi
```
`cat ~/test`

**Comment by luukvbaal** [comment] 2021-05-12 00:19
But this behavior is still specific to the netbsd-curses and musl libc compilation right?

**Comment by luukvbaal** [comment] 2021-05-12 00:35
I see, weird stuff. I'm off to bed for now though, good luck.

**Comment by jarun** [comment] 2021-05-12 01:38
Unrelated to this issue.

I see sabotabge-linux has a [recipe for `nnn`](https://github.com/sabotage-linux/sabotage/blob/master/pkg/nnn) but the version is dated.

@rofl0r can you please update it to use the latest `nnn` v4.0?

**Comment by jarun** [comment] 2021-05-12 03:26
@luukvbaal I have explained the issue in https://github.com/sabotage-linux/netbsd-curses/issues/46. `netbsd-curses` sends a `NULL` (0) which is registered as <kbd>^Space</kbd> (mark range/clear sel keybind) in `nnn`.

See if the flickering issue on `st` is also due to the same problem.

I am considering removing the <kbd>^J</kbd> keybind and just leave the <kbd>m</kbd>. As someone who uses the _nav-to-type_ mode exclusively, I find it hard remembering the <kbd>^Space</kbd> key all the time. Maybe because it's seldom used.

**Closed** 2021-05-12 04:47 UTC
Labels: bug

**Comment by luukvbaal** [comment] 2021-05-12 10:14
No the problem is still there, although it seems to go away after changing directories a few times:
![out](https://user-images.githubusercontent.com/31730729/117956927-d12eed80-b319-11eb-904e-48d68f3ae25f.gif)

Was also able to confirm that it's a problem only occurring with netbsd-curses in combination with the [alpha](https://st.suckless.org/patches/alpha/) patch, issue is not present on `st` master branch. Seems like cells that haven't been written to by netbsd curses are drawn incorrectly by the alpha patch or something.

**Comment by jarun** [comment] 2021-05-12 11:49
Thanks for checking it!

While we are at it, and to have the notes for later, I see another issue with `xfce4-terminal` (no `-n`) where if I keep opening and closing a text file detached in another tab again and again, the window breaks. The statusbar is printed after the last entry. Not sure if it is due to the same redraw issue we reported.

If I repeat the open and close the file once or twice, the problem goes away.


[![Asciicast](https://asciinema.org/a/aFhBcmqYRR99BvOtTR5AMvUy5.svg)](https://asciinema.org/a/aFhBcmqYRR99BvOtTR5AMvUy5)

[![Asciicast](https://asciinema.org/a/zJ43P42qgWQn3J7vWkx5RU3HH)](https://asciinema.org/a/zJ43P42qgWQn3J7vWkx5RU3HH.svg)
