### ISSUE TITLE
`S` is not operating same as in 2.0

### ISSUE THREAD

**Issue by danielb2** [jarun/nnn#206] opened 2019-02-06 17:55 UTC
preciously (in version 2.0) when choosing `S` the size would be calculated immediately. Now I have to enter a folder and hit back before it gets everything sorted and calculated. 

btw, it would be nice if nnn didn't lock up when doing operations. That's what makes it the least user friendly right now. Otherwise I love it.

**Comment by jarun** [comment] 2019-02-07 02:25
> Now I have to enter a folder and hit back

Please test on master. I just tested it and it seems it is fixed.

> nnn didn't lock up when doing operations

What is the issue you see?

**Comment by danielb2** [comment] 2019-02-07 03:32
Yes, it works in master.

> What is the issue you see?

For instance, when doing into a directory that's got very large subdirs, calculating the size of the directories doesn't appear to be cached in anyway, and it locks the FM. It would be a better experience if the dirs  got sorted as their size finished even if it doesn't not immediately provide the complete picture.

**Comment by jarun** [comment] 2019-02-07 03:59
> if the dirs got sorted as their size finished

That would need take the process to take much more time to complete. Also, the first instance takes time, the second time the results come _mostly_ from the cache. Here are my results:

```
## Fired `nnn` in my home dir.
     - all cached, no major page faults
  
  ~$ /usr/bin/time -v nnn
  	Command being timed: "nnn"
  	User time (seconds): 0.00
  	System time (seconds): 0.00
  	Percent of CPU this job got: 0%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:03.77
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3400
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 274
  	Voluntary context switches: 6
  	Involuntary context switches: 1
  	Swaps: 0
  	File system inputs: 0
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
  
  ## Fired `nnn` on an external disk root in du mode, went into a subdir, came back to root.
     - no major page faults
     - File system inputs: 14680
     - 220 KB cached extra
  
  ~$ /usr/bin/time -v nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/
  	Command being timed: "nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/"
  	User time (seconds): 0.02
  	System time (seconds): 0.27
  	Percent of CPU this job got: 3%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:08.30
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3620
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 337
  	Voluntary context switches: 576
  	Involuntary context switches: 2
  	Swaps: 0
  	File system inputs: 14680
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
  
  ## Fired `nnn` again (around 2 mins later, I was formatting the above text) on the external disk root in du mode.
     - File system inputs: 0
  
  ** So even between 2 distinct instances of nnn, _all_ the data fetched in the first instance remained cached.
  
  ~$ /usr/bin/time -v nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/
  	Command being timed: "nnn -S /media/vaio/49462fdf-010c-40cc-89db-ef125e7dae99/tmp/"
  	User time (seconds): 0.00
  	System time (seconds): 0.01
  	Percent of CPU this job got: 0%
  	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:02.31
  	Average shared text size (kbytes): 0
  	Average unshared data size (kbytes): 0
  	Average stack size (kbytes): 0
  	Average total size (kbytes): 0
  	Maximum resident set size (kbytes): 3616
  	Average resident set size (kbytes): 0
  	Major (requiring I/O) page faults: 0
  	Minor (reclaiming a frame) page faults: 329
  	Voluntary context switches: 5
  	Involuntary context switches: 0
  	Swaps: 0
  	File system inputs: 0
  	File system outputs: 0
  	Socket messages sent: 0
  	Socket messages received: 0
  	Signals delivered: 0
  	Page size (bytes): 4096
  	Exit status: 0
  ~$
```

**Comment by jarun** [comment] 2019-02-07 04:27
Closing as the issue is fixed on master.

**Closed by jarun** 2019-02-07 04:27 UTC

**Comment by jarun** [comment] 2019-02-07 20:35
Thanks for the proposal for some more visual feedback. I have added some changes at commit c07efcacc0f25391529a539138832948eccc8bf1 to show the current directory being scanned at the bottom.

This is the best I can do right now. A redraw has some side-effects which I don't have the bandwidth to debug.

**Comment by danielb2** [comment] 2019-02-07 20:45
thanks for this!

**Comment by danielb2** [comment] 2019-02-07 20:47
oh another would be to listen for ctrl+c and stop and print whatever it had time with so far. it locks completely currently

**Comment by jarun** [comment] 2019-02-07 20:50
That's a little weird. SIGINT is ignored and it works correctly for me.

Which distro are you on? What happens if you press ^C on a normal screen?

**Comment by danielb2** [comment] 2019-02-07 20:56
macOS sierra.  normal screen ?

**Comment by danielb2** [comment] 2019-02-07 20:57
same issue on FreeBSD too

**Comment by jarun** [comment] 2019-02-07 20:58
Use the latest master.

normal screen -> the regular screen when you fire `nnn`.

**Comment by danielb2** [comment] 2019-02-07 21:04
freebsd version readline.h was missing so I didn't compile latest master there.

if I do SIGINT on normal screen nothing happens. I would like size calc to stop if I do it otherwise tho.

**Comment by jarun** [comment] 2019-02-07 21:12
> I would like size calc to stop if I do it otherwise tho.

I have some points here:

- nothing really hangs. `nnn` would come back and show you the `du` information.
- `nnn` takes much less time (or equivalent) than any other utility for `du`
- the visual feedback I have added now should improve the experience
- the waiting time is much less the second time around as you would see in the cache hit data above

With the above points I am not making any further changes to this workflow. You can raise a PR if you have something and I will review it.

**Comment by danielb2** [comment] 2019-02-07 21:26
I'm using "hangs" to specify that the interface to the app becomes completely frozen while waiting for the results from `du`.  on my mac, this can take a long time (for whatever reason).

**Comment by jarun** [comment] 2019-02-07 22:15
Here's my data:

```
du

0.21user 0.64system 0:00.86elapsed 99%CPU (0avgtext+0avgdata 18136maxresident)k
0inputs+0outputs (0major+8559minor)pagefaults 0swaps

nnn

0.08user 0.62system 0:00.71elapsed 99%CPU (0avgtext+0avgdata 4060maxresident)k
0inputs+16outputs (0major+1053minor)pagefaults 0swaps
```

**Comment by jarun** [comment] 2019-02-08 02:29
You know that your disk is slow, still you **repeat** pressing `^J` due to some unknown reason and you want to cancel it as well. I don't see the point behind your workflow.

I think you are just pushing to get the cancellation implemented. I can't do that without a valid reason.

**Comment by danielb2** [comment] 2019-02-08 04:51
I start with `nnn -S` and I don't keep pressing ^J. I've never used this command.
My harddrive was full so I was using nnn to figure out what to delete. and btw, the delete function also locks the interface.   Either way, it meant going in and out of folders, and having it recalculate as I went. 

I'm not pushing anything. I like your app, and I was just saying what would make it better for me. Do whatever you want.  I can't say I feel like your tone is friendly at this point though, so I'm done.

**Comment by jarun** [comment] 2019-02-08 05:35
Still my question applies. Why not start with `nnn` instead of `nnn -S`?

**Comment by jarun** [comment] 2019-02-08 13:58
> the delete function also locks the interface

because after delete it needs to recalculate the du again with the contents left in the directory

> My harddrive was full so I was using nnn to figure out what to delete.

So this is not your regular use case. The du mode is mostly used for the same purpose and once the target files are detected the user switches back to `nnn` (instead of `nnn -S`). `du` is processing and time intensive.

**Comment by jarun** [comment] 2019-02-08 15:12
> I can't say I feel like your tone is friendly

No, I wanted to understand the problem at a level where I can decide it's really a use case I must take care of.

`du` abort is implemented at commit 2f32c32c7b1290e27fd0d51b35aaa93bcb129971.

Please test and confirm it works. The SSD on my workstation is so fast I can't time the cancellation.

**Comment by danielb2** [comment] 2019-02-08 17:42
ah, yes. this is great. Thank you so much.

after the abort, the screen needs a refresh (^L) since the screen renders empty

**Comment by jarun** [comment] 2019-02-08 17:47
Thanks for confirming!

> after the abort, the screen needs a refresh (^L) since the screen renders empty

Yes, that's what I though would happen. Can you confirm if commit 027af53ae0b57538166c9888b675d2ce4c979355 fixes this?

**Comment by danielb2** [comment] 2019-02-08 17:57
confirmed :)

btw, it's not necessarily that my disk is slow (it's an SSD, but due to encryption, it is) but I also have some folders on my FreeBSD NAS that are simply huge.

**Comment by jarun** [comment] 2019-02-08 18:03
> it's not necessarily that my disk is slow

Yes, I had to think wider to get that but eventually I figured it out that network mounted devices would always be an issue, irrespective of the hardware. ;)

**Comment by jarun** [comment] 2019-02-08 18:06
Thanks a lot for your patience! :+1: 

I generally try to understand the problem reasonably so I don't have to rollback.

**Comment by jarun** [comment] 2019-02-08 18:40
Please give commit 1253e462b83c1fa5ba928907d68159af4e9f8170 a try. I have used `sigaction()` which is the recommended way. Please try multiple aborts in the same instance of `nnn`.

**Comment by danielb2** [comment] 2019-02-08 20:35
works well too :)

**Comment by jarun** [comment] 2019-02-08 20:56
Awesome!
