### ISSUE TITLE
`preview-tui` offsets image preview

### ISSUE THREAD

**Issue by tapyu** [jarun/nnn#1746] opened 2023-10-09 13:51 UTC
Whenever I start the image preview, the image is shown in the correct position. However, the next images has an offset wrt its correct position.

![nnn](https://github.com/jarun/nnn/assets/22801918/1e41ec2a-1e58-4593-94b7-537c2785e3e9)

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Linux
- [x] Desktop Environment: GNOME
- [x] Terminal Emulator: Kitty
- [x] Shell: zsh
- [x] Configuration options set:
- [x] Plugins are installed: `p:preview-tui`
- [ ] Issue exists on `nnn` master

Kitty configuration:

```
# The value of the TERM environment variable to set
term xterm-kitty

# Font size (in pts)
font_size        22.0

# font
font_family      MesloLGMDZ Nerd Font
italic_font      MesloLGMDZ Nerd Font
bold_font        MesloLGMDZ Nerd Font
bold_italic_font MesloLGMDZ Nerd Font

# The foreground color
foreground       #c0b18b

# The background color
background       #262626

# The foreground for selections
selection_foreground #2f2f2f

# The background for selections
selection_background #d75f5f

# The cursor color
cursor           #8fee96

# The cursor shape can be one of (block, beam, underline)
shell_integration no-cursor
cursor_shape beam

# The interval (in seconds) at which to blink the cursor. Set to zero to
# disable blinking.
cursor_blink_interval     0

# hide top bar window decoration
hide_window_decorations yes

# Allow other programs to control kitty.
allow_remote_control yes
listen_on unix:/tmp/kitty
```

**Comment by luukvbaal** [comment] 2023-10-10 23:35
Can't reproduce this one. `preview-tui` just passes a hardcoded `0x0` as the offset for the icat kitten when using kitty so I'm not sure we're responsible for any offset.

**Comment by tapyu** [comment] 2023-10-11 11:01
Everything indicates that is a `nnn`'s problem. More precisely, an `preview-tui`'s problem. Under the [`image_preview()`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L420), I am just echoing the input arguments to `icat` to a file and I am `watch`ing it. `nnn` provides the correct XxY location at the startup. but when I go through the files, `nnn` passes the an shifted XxY position.

Take a look:

![nnn3](https://github.com/jarun/nnn/assets/22801918/d1fbe361-54dd-440e-908f-299ec8c0d4d6)

**Comment by luukvbaal** [comment] 2023-10-11 12:48
Those are not the XxY offsets but rather the widthxheight. The fact that it changes to 80 x 24 is unexpected, but not directly related to the offset...

80 x 24 are the default terminal dimensions `tput` reports when it can't detect the actual size. So something is breaking that. I don't know what, still can't reproduce.

**Comment by tapyu** [comment] 2023-10-11 18:43
> 80 x 24 are the default terminal

It seems to be the default values as they repeat to any image I select:

```
80 24 /home/tapyu/Pictures/Hessian.jpg
80 24 /home/tapyu/Pictures/DFT.jpg
80 24 /home/tapyu/Pictures/Bayes.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-04-20 02-17-58.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-04-24 05-11-20.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-04-24 05-55-37.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-00-18.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-04-18.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-05-39.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-09-58.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-20-50.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-24-25.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-26-19.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-34-59.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-09 09-38-19.png.jpg
80 24 /tmp/nnn/previews//home/tapyu/Pictures/Screenshots/Screenshot from 2023-05-10 21-34-54.png.jpg
```

> Those are not the XxY offsets but rather the widthxheight.

It makes no sense, though. How could 80x24 be widthxheight if the images' ratio aren't changed? Instead, their positioning on the screen change, which makes me deduce that it is the XxY position of the image....

**Comment by luukvbaal** [comment] 2023-10-11 18:54
It's (supposed to be) the dimensions of the terminal pane `preview-tui` runs in, not the image.

**Comment by tapyu** [comment] 2023-10-12 13:17
I've found the problem. `tput` cannot correctly return the terminal dimension within a background function, which occurs in the [`toggle_preview()`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L491) function, when `preview-tui` is called at the first time (without the `PREVIEW_MODE` set), and in `preview_fifo` (when `PREVIEW_MODE` is set).

In your machine, check if the `tput` output before calling these function and within these function. In my computer, before entering these function, `tput lines` is 28 and `tput cols` is 120 (that is correct), and within these function, `tput lines` is 24 and `tput cols` is 80.

**Comment by luukvbaal** [comment] 2023-10-12 13:50
Yes on my machine it is always correct. Like I said before simmilar problems popped up like a year ago, it was fixed in a later `ncurses` version. What version are you on?

**Comment by tapyu** [comment] 2023-10-12 14:20
```
tapyu@tapyu-ThinkPad-P73 
------------------------ 
OS: Ubuntu 22.04.3 LTS x86_64 
Host: 20QRCTO1WW ThinkPad P73 
Kernel: 6.2.0-34-generic 
Uptime: 6 hours, 30 mins 
Packages: 3003 (dpkg), 14 (snap) 
Shell: zsh 5.9 
Resolution: 3840x2160 
DE: GNOME 44.3 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: kitty 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: NVIDIA Quadro P620 
GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
Memory: 6337MiB / 23662MiB 
```

```
❯ nnn -V
4.7
```

**Comment by luukvbaal** [comment] 2023-10-12 14:22
I meant what `ncurses` version, try `tput -V`.

**Comment by tapyu** [comment] 2023-10-12 14:28
I am sorry, but what is `ncurses`? I've googled it but I didn't get it exactly. Is that a `C` library?

**Comment by tapyu** [comment] 2023-10-12 14:28
```
❯ tput -V
ncurses 6.4.20221231
```

**Comment by luukvbaal** [comment] 2023-10-12 14:32
OK so not the version that was found to be broken in https://github.com/jarun/nnn/issues/1228, IDK then.

**Comment by tapyu** [comment] 2023-10-12 15:06
When I startup the `preview-tui` plugin, the following command sequence happens:

1- [`preview_file`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L477) is called (not in background).
1- If I call it with a selected image file, `preview_file` calls [`handle_mime`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L362) (not in background)
1- it calls [`image_preview`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L258) (not in background) (it can also call `generate_preview` if it isn't a `jpeg` file) (`jpeg_preview` would be a more descriptive name).
1- Finally, [`icat`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L420) is called with the correct `tput` output bacause there aren't background function at the beginning.

At this point, the named pipe isn't used. When it goes back to [`preview_fifo &`](https://github.com/jarun/nnn/blob/7f63bef4d6c9f70b99a4c98435c9c0a68e05be44/plugins/preview-tui#L478), it reads from the named pipe, but with the wrong `tput` outputs, which makes the remaining image previews be shifted.

**Comment by luukvbaal** [comment] 2023-10-12 15:14
Yes, this is all apparent. The question is why `tput` reports incorrect dimensions on your system.

**Comment by tapyu** [comment] 2023-10-12 15:33
I've found the problem (again)! The issue isn't exactly backgrounding the function, but is redirecting its STDOUT and STDERR to `/dev/null`. In this MWE shell script:

```sh
#!/bin/sh

fun(){
echo "That is a shell function that will run in background" >> $HOME/test.log
echo "inside the function: tput lines is $(tput lines)" >> $HOME/test.log
echo "inside the function: tput cols is $(tput cols)" >> $HOME/test.log
} >/dev/null 2>&1

fun "test" &
sleep 1
echo "in the shell script scope: tput lines is $(tput lines)" >> $HOME/test.log
echo "in the shell script scope: tput cols is $(tput cols)" >> $HOME/test.log
```

In my machine, I get
```
❯ \cat test.log
That is a shell function that will run in background
inside the function: tput lines is 24
inside the function: tput cols is 80
in the shell script scope: tput lines is 28
in the shell script scope: tput cols is 120
```

That is the bug's origin.

**Comment by tapyu** [comment] 2023-10-12 15:37
If you remote `>/dev/null 2>&1`, we get

```
❯ \cat test.log
That is a shell function that will run in background
inside the function: tput lines is 28
inside the function: tput cols is 120
in the shell script scope: tput lines is 28
in the shell script scope: tput cols is 120
```

**Comment by luukvbaal** [comment] 2023-10-12 15:40
Right, which is why we removed it in https://github.com/jarun/nnn/pull/1431. Are you using `preview-tui` from master?

**Comment by tapyu** [comment] 2023-10-13 17:57
@luukvbaal  I discovered from where I got the outdated plugins! It tuns out the this shell script is not downloading most updated plugin versions.

[Screencast from 13-10-2023 14:51:37.webm](https://github.com/jarun/nnn/assets/22801918/8e313b38-035e-4acd-843e-686286cbde6f)


Take a look. From the master branch and on another machine (I have two computers), this script is downloading some previous version of `preview-tui` which contains the `2>/dev/null`

I didn't look this script yet, but there is probably some but in it.

**Comment by tapyu** [comment] 2023-10-13 18:12
The problem is because this machine runs on Ubuntu 22.04, which provides

```sh
❯ nnn -V
4.3
```

The file `https://github.com/jarun/nnn/releases/download/v4.3/nnn-v4.3.tar.gz` is outdated and provides a bugged `preview-tui`. 

Shouldn't be better to always provide the most updated plugins version regardless the `nnn` version?

**Comment by luukvbaal** [comment] 2023-10-13 18:33
Yes like I said the `getplugs` script doesn't download the latest version by default https://github.com/jarun/nnn/issues/1746#issuecomment-1759909457...

> Shouldn't be better to always provide the most updated plugins version regardless the nnn version?

I think so too, @jarun disagrees.

**Closed by luukvbaal** 2023-10-13 18:33 UTC
Labels: bug

**Comment by N-R-K** [comment] 2023-10-13 18:39
> Shouldn't be better to always provide the most updated plugins version regardless the `nnn` version?

The plugins might be updated in a way that makes it work only on `master` nnn and break on older nnn version. I don't think this has happened much though. But both sides (fetch master vs stable) has downsides.
