### ISSUE TITLE
Had to create /nnn/ folder by hand

### ISSUE THREAD

**Issue by conilas** [jarun/nnn#343] opened 2019-10-08 12:07 UTC
#### BUG REPORT 

**Environment**
Shell:  bash
Terminal (probably not important): terminator

So, after adding the `n` call to my bashrc and sourcing it, I tried to use `n`, navigate to a folder and Ctrl+G. 

The expected behavior would be for it to CD to that folder. Instead, nothing happened. 

I went to check in the `~/.config` folder (where it saves the latest used by nnn according to https://github.com/jarun/nnn/wiki/Basic-use-cases#configure-cd-on-quit) and I did not have the /nnn/ folder. 

After creating it, everything went fine.

If this is intended behavior, maybe it should be documented on the already mentioned link (I can create a pull req for it!). If it is not, it would classify as a bug (I guess)

**Comment by jarun** [comment] 2019-10-08 12:31
It's a bug. Can you please remove the `~/.config/nnn` directory and compile in debug mode? The debug logs should show more info.

**Comment by jarun** [comment] 2019-10-08 14:07
In addition please check if you have `$XDG_CONFIG_HOME` defined. It doesn't look feasible from the code `nnn` will start without creating the config directory.

**Comment by 0xACE** [comment] 2019-10-08 17:12
I cannot reproduce this on the latest master. My best guess atm is that your machine is misconfigured.

Btw I dont have `$XDG_CONFIG_HOME` defined, and it works fine.

**Comment by jarun** [comment] 2019-10-10 03:01
@conilas we can't proceed without addition details. Closing the issue.

**Closed by jarun** 2019-10-10 03:01 UTC
