### ISSUE TITLE
cp as not working on macOs

### ISSUE THREAD

**Issue by eaparnell** [jarun/nnn#785] opened 2020-11-17 22:08 UTC
I am running os X Mojave and nnn 3.4 under tmux.
I select a file in the source directory by pressing <space>. Then navigate to target directory and press w.
My vi editor pops up with the full file path of the selected file. I change the full path to the full path I want it copied to, save the file and get the message "failed!" briefly on the status line.

I also tried just change the line in the editor just to the name of the file (e.g. test.pdf) and that did not work either. 
Any thoughts? Any debug flags I can turn on to get more diagnostic info? Many thanks.

**Comment by jarun** [comment] 2020-11-17 22:19
Looks like a duplicate of defect #728. Please try `nnn` v3.5 along with GNU sed.

Note: you select by pressing <kbd>Space</kbd>.

**Closed by jarun** 2020-11-17 22:19 UTC
Labels: bug
