### ISSUE TITLE
preview-tui: 1: eval: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by FunctionDJ** [jarun/nnn#1895] opened 2024-06-12 08:38 UTC
When i try to use the `preview-tui` plugin while hovering on a folder that's named something like this `Foo (Bar) [Bat]`, the plugin doesn't work and `preview-tui: 1: eval: Syntax error: "(" unexpected` is logged which is visible when exiting `nnn` afterwards.

I'm running `nnn` on a remote machine with `tmux` for the tiling.

I've looked at probably related issues and PRs like #1617 and #1614 but couldn't figure out if there is a fix for this.

#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Kubuntu 24.04 LTS (local machine), Ubuntu 23.10 (remote server)
- [x] Desktop Environment: Plasma 5.27.11 (local), none (remote)
- [x] Terminal Emulator: KDE Konsole (local)
- [x] Shell: GNU bash, version 5.2.15 (remote)
- [x] Custom desktop opener (if applicable): none
- [x] Program options used: none
- [x] Configuration options set: `NNN_PLUG='p:preview-tui'` `NNN_FIFO="/tmp/nnn.fifo"` `NNN_OPTS='H'`
- [x] Plugins are installed
- [ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
- install plugins
- add `preview-tui` to `NNN_PLUG`
- `tmux`
- `touch 'foo (bar)'`
- `nnn`
- highlight `foo (bar)` file
- trigger `preview-tui` plugin
- plugin won't launch and upon exiting `nnn`, a line containing "syntax error" will be shown before the prompt

**Comment by N-R-K** [comment] 2024-06-13 00:57
The [issue template](https://github.com/jarun/nnn/blob/90eb2d32c0fe226f693172d2c1d2e364fb99a55e/.github/ISSUE_TEMPLATE/bug_report.md?plain=1#L30) asks for some environment details. Please provide them, especially your bash version and preview-tui version.

**Comment by FunctionDJ** [comment] 2024-06-13 08:41
@N-R-K pardon, i didn't look at the bug template correctly and deleted everything instead of what i should. i have edited the issue above.

regarding the preview-tui version, i don't know where i can find it. i've read the plugin file at `~/.config/nnn/plugins/preview-tui` and no version is mentioned there. i'm running `nnn` v4.8.1 though.

regarding "Issue exists on `nnn` master", i don't really know how to build binaries and i was hoping that it's okay to open issues without being able to compile `nnn`.

**Comment by N-R-K** [comment] 2024-06-13 11:07
> regarding the preview-tui version, i don't know where i can find it.

It doesn't have an explicit version. I'm going to assume that it's the one that came with your nnn version.

> i'm running nnn v4.8-1

There were some fixes made to preview tui since 4.8. Try downloading the latest one from master and see if that fixes your issue.

> nnn -V doesn't appear to list the -1

That `-1` part is probably ubuntu's package revision number.

**Comment by N-R-K** [comment] 2024-06-13 23:59
> the plugin doesn't work and preview-tui: 1: eval: Syntax error: "(" unexpected is logged which is visible when exiting nnn afterwards

I tried this on master and cannot reproduce. Also, the current preview-tui script doesn't have any `eval` since commit 432b0755d33f5d7c0f9e085939338aa0644c17e9.

I'm closing this off as fixed by 432b0755d33f5d7c0f9e085939338aa0644c17e9.

**Closed by N-R-K** 2024-06-13 23:59 UTC
Labels: bug

**Comment by FunctionDJ** [comment] 2024-06-28 09:37
@N-R-K i was finally in a situation where i could upgrade to Ubuntu 24 LTS, shipping nnn 4.9 in their repo.

Unfortunately despite removing and reinstalling the plugins, the `preview-tui` plugin seems to be broken for me. When i trigger the plugin, it prints `size missing` right into `nnn` on top of the first entry, without creating a tmux split.

**Comment by thezacharytaylor** [comment] 2024-09-18 16:30
I have this issue on Mac 14.6.1 Sonoma. I've replaced the preview-tui code after it didn't work redownloading it, but it persists.
