### ISSUE TITLE
Distro-specific packages 

### ISSUE THREAD

**Issue by daniel-vera-g** [jarun/nnn#1071] opened 2021-06-13 09:30 UTC
Hey, I noticed that for the last two releases the Distro-specific packages are located on OBS.

I run Ubuntu v18.04 and till nnn v.4.0 there was a specific `.deb` for this version. OBS only gives me the option for the v20.04 Version.

Is this a premanent change? The nnn version from the package managers are pretty old, so I would have to get directly the binary.

**Comment by jarun** [comment] 2021-06-13 09:33
@Stig124 @dilawar 

There are some issues with generating the older release packages on OBS.
We will try to get it working. Need some time.

**Comment by Stig124** [comment] 2021-06-13 09:36
> Hey, I noticed that for the last two releases the Distro-specific packages are located on OBS.
> 
> I run Ubuntu v18.04 and till nnn v.4.0 there was a specific `.deb` for this version. OBS only gives me the option for the v20.04 Version.
> 
> Is this a premanent change? The nnn version from the package managers are pretty old, so I would have to get directly the binary.   

Hello,

This is a known issue with dependencies on OBS for Debian builds, I'm in the progress of fixing it

**Comment by daniel-vera-g** [comment] 2021-06-13 09:42
Ok, thanks for the quick update  :+1:

**Comment by Stig124** [comment] 2021-06-21 16:08
@daniel-vera-g Good news, the issue is fixed so the packages for Ubuntu 16/18 and *bian 9 are up on the OBS

Closing this issue

**Closed by Stig124** 2021-06-21 16:08 UTC
Labels: work in progress
