### ISSUE TITLE
some icon is truncated some not

### ISSUE THREAD

**Issue by simona70** [jarun/nnn#1058] opened 2021-06-06 14:14 UTC
![Screenshot_20210606_161359](https://user-images.githubusercontent.com/41611485/120927759-43f57380-c6e2-11eb-8137-ae1d057fd7d0.jpeg)

**Comment by jarun** [comment] 2021-06-06 14:18
Looks to a duplicate of #969.

@luukvbaal can you please add the necessary notes in the WIki Troubleshooting section?

**Comment by luukvbaal** [comment] 2021-06-06 14:26
It does look like a similar problem. #969 presents a solution for `st` though and this doesn't look like `st` to me.
If it is some kind of `st` gui wrapper you can try the patch but otherwise your best bet would be to switch to a different terminal where the issue isn't present(e.g. `alacritty/kitty`).

Still wondering if this issue can't be fixed on `nnn` side as I had never seen the truncated icons outside of `nnn` and remember the issue being semi-fixed by some iterations of my namefirst patch before I applied the st fix that fixes it altogether.

**Closed** 2021-06-06 14:27 UTC
Labels: bug

**Comment by KlzXS** [comment] 2021-06-06 14:32
> Still wondering if this issue can't be fixed on nnn side

This has to do with the way the terminal renders these icons. `nnn` can't do much there. We could try printing the icon last. That should in theory print it on top of everything else.

Not sure if that would affect performance. I don't think it would be noticable.
