### ISSUE TITLE
nnn functions strangely when being used in /tmp

### ISSUE THREAD

**Issue by orf** [jarun/nnn#65] opened 2017-12-25 17:03 UTC
If I run `nnn` inside `/tmp`, on MacOS Sierra, the display seems to function at first. However if you use the arrow keys then the display becomes corrupted and seems to not function (see below). It works fine *in the same terminal* when run from my home directory, or the root directory.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1027207/34341718-5f673852-e995-11e7-9a68-c36c02b07ae5.png">

**Comment by jarun** [comment] 2017-12-25 17:07
I believe this is already fixed at 8307bc95bd4e0f07e3dd0e3e114e7f0595a95585. The fix is in just-released v1.6. Homebrew is still at v1.5. Please check with v1.6 when it's available on Homebrew and confirm.

**Comment by orf** [comment] 2017-12-25 17:13
Oh my, sorry, I naively assumed I was using 1.6, but I'm on 1.5. My bad!

**Comment by jarun** [comment] 2017-12-25 17:19
No problem! Please let us know if it works.

**Comment by jarun** [comment] 2017-12-26 02:29
I am closing this as I am pretty sure the issue is due to FIFO file detail prints using printf() from your screenshot. Please reopen if that's not the case.

**Closed by jarun** 2017-12-26 02:29 UTC
