### ISSUE TITLE
Problem using kitty preview

### ISSUE THREAD

**Issue by basbebe** [jarun/nnn#614] opened 2020-05-30 10:56 UTC
I'm having a similar problem like https://github.com/jarun/nnn/issues/578 (preview pane closes immediatley after opening).
`kitty @ launch man man` works fine.

I'm calling `NNN_PLUG='p:kitty-preview' n -a`.
When I open the plugin I see a short flicker of the preview, then it's gone.

This is my env:

```
COLORTERM=truecolor
DISPLAY=/private/tmp/com.apple.launchd.BGywV6KAIn/org.macosforge.xquartz:0
EDITOR=kak
HOME=/Users/bastian
HOMEBREW_GITHUB_API_TOKEN=XXXXXXXX
KITTY_WINDOW_ID=8
LANG=de_DE.UTF-8
LESS=-g -i -M -R -S -w -z-4
LESSOPEN=|/usr/local/bin/lesspipe.sh %s
LESS_ADVANCED_PREPROCESSOR=1
LOGNAME=bastian
MANPAGER=sh -c 'col -bx | bat -l man -p'
NNN_ARCHIVE=\.(7z|bz2|gz|tar|tgz|zip)
NNN_BMS=d:~/Documents;u:~/;D:~/Downloads/
NNN_COLORS=1234
NNN_OPENER=/Users/bastian/.config/nnn/plugins/nuke
NNN_PLUG=f:finder;o:fzopen;p:preview-kitty;d:diffs;t:nmount;v:imgview;g:-_git diff;l:-_git log;b:-_bat $nnn*;s:-pdfview
PAGER=less
PATH=/usr/local/bin:/usr/local/sbin:/Users/bastian/.local/bin:/Users/bastian/.cache/dein/repos/github.com/junegunn/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS
PWD=/Users/bastian
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.dXY9WGEm9I/Listeners
STARSHIP_SHELL=fish
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Frameworks/kitty/terminfo
TMPDIR=/var/folders/7w/jr1m8lhx12sfmydz5b7gklrw0000gn/T/
USER=bastian
VISUAL=kak
XPC_FLAGS=0x0
XPC_SERVICE_NAME=net.kovidgoyal.kitty.29400
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x3
```

**Comment by jarun** [comment] 2020-05-30 10:58
Where's `NNN_FIFO`?

**Comment by basbebe** [comment] 2020-05-30 11:05
Sorry, forgot to include it.

It works with `NNN_FIFO=/tmp/nnn.fifo NNN_PLUG='p:preview-tui' nnn`. A XQuarty window opens with `less` in it.

with `NNN_FIFO=/tmp/nnn.fifo NNN_PLUG='p:preview-kitty' n -a` there's only a short flicker.

**Comment by jarun** [comment] 2020-05-30 11:34
See the documentation in the kitty file for instructions. Ensure you follow those.

**Comment by basbebe** [comment] 2020-05-30 11:35
I did follow the instructions in https://github.com/jarun/nnn/blob/master/plugins/preview-kitty

**Comment by jarun** [comment] 2020-05-30 12:58
> kitty (https://sw.kovidgoyal.net/kitty/) with allow_remote_control on

This setting is required.

Also, `NNN_FIFO=/tmp/nnn.fifo NNN_PLUG='p:preview-kitty' n -a`

Can you drop the `-a`? Why do you need to define both `NNN_FIFO` and use `-a`?

@leovilok any ideas?

**Comment by basbebe** [comment] 2020-05-30 13:03
> This setting is required.

Yes.
`kitty @ launch man man` works.

> Can you drop the -a? Why do you need to define both NNN_FIFO and use -a?
I trief combinations, the result stays the same…

**Comment by jarun** [comment] 2020-05-30 13:11
@midexe6380 would you be able to help here?

**Comment by leovilok** [comment] 2020-05-30 22:19
@basbebe does `preview-tui` works?

**Comment by kuntau** [comment] 2020-05-31 06:02
Same here.. can't get preview working.. `-a` switch is invalid in osx

**Comment by jarun** [comment] 2020-05-31 06:14
> Same here.. can't get preview working.. -a switch is invalid in osx

The feature is available in `nnn` v3.2

**Comment by basbebe** [comment] 2020-05-31 10:57
Could it have to do with `$PATH` or another environment variable?
I`m on a Mac.
`Kitty @ launch` works however.

```
kitty 0.17.4 created by Kovid Goyal
Darwin Bastians-MBP.fritz.box 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
ProductName:	Mac OS X ProductVersion:	10.15.4 BuildVersion:	19E287
Loaded config files: /Users/bastian/.config/kitty/kitty.conf

Config options different from defaults:
active_border_color  Color(red=184, green=186, blue=37)
adjust_line_height   1.2
allow_remote_control y
background           Color(red=40, green=40, blue=40)
color0               Color(red=40, green=40, blue=40)
color1               Color(red=204, green=36, blue=29)
color10              Color(red=184, green=187, blue=38)
color11              Color(red=250, green=189, blue=45)
color12              Color(red=131, green=165, blue=152)
color13              Color(red=211, green=134, blue=155)
color14              Color(red=142, green=192, blue=124)
color15              Color(red=146, green=131, blue=116)
color2               Color(red=152, green=151, blue=26)
color3               Color(red=215, green=153, blue=33)
color4               Color(red=69, green=133, blue=136)
color5               Color(red=177, green=98, blue=134)
color6               Color(red=104, green=157, blue=106)
color7               Color(red=168, green=153, blue=132)
color8               Color(red=146, green=131, blue=116)
color9               Color(red=251, green=73, blue=52)
cursor               Color(red=146, green=131, blue=116)
editor               /usr/local/bin/kak
env                  {'LANG': 'de_DE.UTF-8', 'PATH': '/usr/local/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/local/sbin:/Users/bastian/.local/bin:/Users/bastian/.cache/dein/repos/github.com/junegunn/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/TeX/texbin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS'}
font_family          Jetbrains Mono
font_size            13.0
foreground           Color(red=235, green=219, blue=178)
macos_option_as_alt  2
macos_thicken_font   0.25
macos_titlebar_color 1
selection_background Color(red=60, green=56, blue=54)
selection_foreground Color(red=146, green=131, blue=116)
shell                /usr/local/bin/fish --login
window_padding_width FloatEdges(left=3.0, top=3.0, right=3.0, bottom=3.0)
Added shortcuts:
	 control+l KeyAction(func='combine', args=(KeyAction(func='clear_terminal', args=['scroll', True]), KeyAction(func='send_text', args=['normal,application', b'\x0c'])))
Changed shortcuts:
	 shift+control+enter KeyAction(func='new_window_with_cwd', args=())
	 super+enter KeyAction(func='new_window_with_cwd', args=())

```

> @basbebe does `preview-tui` works?

yes it does.

**Comment by midexe6380** [comment] 2020-05-31 18:40
@basbebe 
try
1) delete string `NNN_FIFO=/tmp/nnn.fifo` in your .bashrc or .zshrc file
2) in `~/.config/kitty/kitty.conf` should be two string `close_on_child_death no` and `allow_remote_control yes` (by taste `enabled_layouts horizontal`)
3) install [exa](https://github.com/ogham/exa), [bat](https://github.com/sharkdp/bat), [mediaInfo](https://mediaarea.net/en/MediaInfo/Download/Mac_OS)
4) if use [`quitcd`](https://github.com/jarun/nnn/tree/master/misc/quitcd) then should be string [`nnn -a`](https://github.com/jarun/nnn/blob/8549121d86c62406fa5326a3c091d745315cff8b/misc/quitcd/quitcd.bash_zsh#L21)
6) restart your shell
7) run `n`(if use quitcd) or just `nnn -a`

Write me if you still have problems after these actions.

**Comment by midexe6380** [comment] 2020-05-31 18:42
@basbebe As @jarun  said 


> The feature is available in `nnn` v3.2

**Comment by midexe6380** [comment] 2020-05-31 19:03
@basbebe 
i see in your dotfiles function `n` without key `-a`

https://github.com/basbebe/.dotfiles/blob/1c80e5468219b0a8a82bc2ce492ac3d54a865f2f/.zshrc#L58

**Comment by leovilok** [comment] 2020-05-31 20:31
@kuntau did you try `preview-tui`?
`-a` should work on Mac too, when you start `nnn -a`, do you see a `nnn-fifo.xxx` be created in `/tmp`?

**Comment by leovilok** [comment] 2020-05-31 20:44
@basbebe to complement what @midexe6380 said, please try this test protocol:

1. open `nnn -a`
2. press `!` to open a shell in `nnn`
3. in that shell, launch the followin command:
   ~~~sh
   kitty @ launch --no-response --keep-focus cat "$NNN_FIFO"
   ~~~
   It should open an empty kitty pane running cat
4. Press `Ctrl+D` to close the subshell a get back to `nnn`
5. Move the cursor around in `nnn`, you should see the hovered file path get dynamically listed in the other pane.

**Comment by jarun** [comment] 2020-06-01 01:15
@kuntau issue is a local env problem. We already explored it in #617.

**Comment by kuntau** [comment] 2020-06-01 05:33
@leovilok @jarun Thank you. I solved my problem with `preview-tui` 👍

**Comment by jarun** [comment] 2020-06-01 07:32
@kuntau For the sake of other users who may face this issue alter, please leave a note what the problem was.

**Comment by basbebe** [comment] 2020-06-01 08:10
> ```shell
> kitty @ launch --no-response --keep-focus cat "$NNN_FIFO"
> ```
@leovilok 
This works just fine, even with my current setting.

> @basbebe
> i see in your dotfiles function `n` without key `-a`
> 
> https://github.com/basbebe/.dotfiles/blob/1c80e5468219b0a8a82bc2ce492ac3d54a865f2f/.zshrc#L58

Yes that's true. I'm changing a lot an playing around the lst days and I haven't commited yet.



> @basbebe
> try
> 
>     1. delete string `NNN_FIFO=/tmp/nnn.fifo` in your .bashrc or .zshrc file
> 
>     2. in `~/.config/kitty/kitty.conf` should be two strings `close_on_child_death no` and `allow_remote_control yes` (by taste `enabled_layouts horizontal`)
> 
>     3. install [exa](https://github.com/ogham/exa), [bat](https://github.com/sharkdp/bat), [mediaInfo](https://mediaarea.net/en/MediaInfo/Download/Mac_OS)
> 
>     4. if use [`quitcd`](https://github.com/jarun/nnn/tree/master/misc/quitcd) then should be string [`nnn -a`](https://github.com/jarun/nnn/blob/8549121d86c62406fa5326a3c091d745315cff8b/misc/quitcd/quitcd.bash_zsh#L21)
> 
>     5. restart your shell
> 
>     6. run `n`(if use quitcd) or just `nnn -a`
> 
> 
> Write me if you still have problems after these actions.
@midexe6380 
`close_on_child_death no` and `allow_remote_control yes` were already set.

**Comment by midexe6380** [comment] 2020-06-01 10:18
@basbebe  Does not work?

**Comment by basbebe** [comment] 2020-06-01 12:03
> @basbebe  Does not work?

I had the prerequisites and the settings were set so nothing changed…

**Comment by basbebe** [comment] 2020-06-01 12:35
just for reference:

This (run in fish shell) works:

`kitty @ launch --no-response --title "nnn preview" --keep-focus --cwd="$PWD" --env "NNN_FIFO=$NNN_FIFO" --env "PREVIEW_MODE=1" bat --paging=always --decorations=always README.md`

This is the environment I get when I `kitty @ launch nnn`

```
>>> printenv
COLORTERM=truecolor
DISPLAY=/private/tmp/com.apple.launchd.in5c01O5ze/org.macosforge.xquartz:0
EDITOR=/usr/local/bin/kak
HOME=/Users/bastian
HOMEBREW_GITHUB_API_TOKEN=696afd796dd4e7c408358e7ee7adc9616816c1a8
KITTY_WINDOW_ID=71
LANG=de_DE.UTF-8
LOGNAME=bastian
PATH=/usr/local/sbin:/Users/bastian/.local/bin:/Users/bastian/.cache/dein/repos/github.com/junegunn/fzf/bin:/usr/local/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/bastian
SHELL=/usr/local/bin/fish
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZB9rj9zmPj/Listeners
TERM=xterm-kitty
TERMINFO=/Applications/kitty.app/Contents/Frameworks/kitty/terminfo
TMPDIR=/var/folders/7w/jr1m8lhx12sfmydz5b7gklrw0000gn/T/
USER=bastian
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x3
nnn=Applications

'Enter' to continue
```

**Comment by basbebe** [comment] 2020-06-01 18:48
I just manually added PREVIEW_MODE and NNN_FIFO as environment variables in a kitty window and launched `sh preview-kitty`.

It showed the preview of another window running nnn.
so… what other environment variables might be missing from my 'shell-less' kitty window?

**Comment by basbebe** [comment] 2020-06-01 19:55
funny thing: If I have an image selected while starting preview and moving the highlighter before the image is loaded, it works.
The Preview stays and shows the current selection.
But that only works until I close nnn again.

**Comment by basbebe** [comment] 2020-06-01 20:28
I changed the very last line:

```
kitty @ launch --no-response --title "nnn preview" --keep-focus \
      --cwd="$PWD" --env "NNN_FIFO=$NNN_FIFO" --env "PREVIEW_MODE=1" \
      "$0" "$1" > /dev/null
```

to

```
kitty @ launch --no-response --title "nnn preview" --keep-focus \
      --cwd="$PWD" --env "NNN_FIFO=$NNN_FIFO" --env "PREVIEW_MODE=1" \
      "$0" > /dev/null
```

Without "$1", everything seems to work for me right now.

**Comment by jarun** [comment] 2020-06-02 01:11
@basbebe thanks for confirming.

@leovilok is "$1" redundant in this case? If yes, please raise a PR to remove it.

I am closing this issue as the problem is solved in local setup. Personally I didn't notice any issue due to the param in question.

**Closed by jarun** 2020-06-02 01:11 UTC
Labels: bug

**Comment by leovilok** [comment] 2020-06-02 01:37
@jarun we were passing `$1` to be sure that the currently hovered file (when the plugin is launched) is always previewed (even if `nnn` redraws too soon). I don't remember who reported this, but that was the fix.

**Comment by jarun** [comment] 2020-06-02 01:40
Yes, because the first file was not previewed, @basbebe which file are you on when you start the preview? Is it a directory, or not entries in the directory you are in?

**Comment by leovilok** [comment] 2020-06-02 01:42
@jarun For reference, this was added in #561 (in preview-tui, but carried later in preview-kitty), following an issue you raised in #559.

**Comment by jarun** [comment] 2020-06-02 01:44
Yes, when you mentioned I noticed there was an issue previewing the first file.

**Comment by basbebe** [comment] 2020-06-02 05:03
> Yes, because the first file was not previewed, @basbebe which file are you on when you start the preview? Is it a directory, or not entries in the directory you are in?

Textfiles and directories did not work as a first file for me.

Images however (as described above) showed this interesting behavior that if I switch file quick enough before imgcat loaded, the preview did not disappear.

This was reproducible in different folders with different files.

**Comment by jarun** [comment] 2020-06-02 13:14
@leovilok shall we document this in-file?

**Comment by leovilok** [comment] 2020-06-03 03:30
@jarun Do you mean documenting which line to remove when the first file makes the previewer crash?
I think that it sounds like a bug that needs to get fixed anyways, and @basbebe can reproduce it.

@basbebe can you try this version of the script?
http://vgx.fr/preview-kitty-checkarg
I'm trying to figure-out why the first file might cause issues.
Also with your version with $1 removed, did you notice that sometimes the first file is not previewed until you move the cursor? (the file hovered when you start the plugin).

**Comment by jarun** [comment] 2020-06-03 03:32
> I think that it sounds like a bug that needs to get fixed anyways

You are right.

**Comment by basbebe** [comment] 2020-06-04 19:20
> @basbebe can you try this version of the script?
> http://vgx.fr/preview-kitty-checkarg

The Problem remains: I only get a persisting preview window if I start with an image and move my selection before the image loads.

> Also with your version with $1 removed, did you notice that sometimes the first file is not previewed until you move the cursor? (the file hovered when you start the plugin).

With my version it is never shown (preview/window remains blank until I change selection).

**Comment by leovilok** [comment] 2020-06-04 20:10
OK, it's time to get serious with remote debugging then, let's try tracing what's happening, @basbebe please try this version:
http://vgx.fr/preview-kitty-traced
And show us the generated `/tmp/preview-kitty-err.log`

**Comment by basbebe** [comment] 2020-06-05 07:04
Thank you very much for your support!

`/tmp/preview-kitty-err.log`

```
+ : starting 85373
+ '[' '' ']'
+ kitty @ launch --no-response --title 'nnn preview' --keep-focus --cwd=/Users/bastian/.config/nnn/plugins --env NNN_FIFO= --env PREVIEW_MODE=1 preview-kitty-traced ''
+ : starting 86225
+ '[' '' ']'
+ kitty @ launch --no-response --title 'nnn preview' --keep-focus --cwd=/Users/bastian/Pictures --env NNN_FIFO=/tmp/nnn-fifo.86219 --env PREVIEW_MODE=1 /Users/bastian/.config/nnn/plugins/preview-kitty Lightroom
+ : starting 86227
+ '[' 1 ']'
+ '[' '!' -r /tmp/nnn-fifo.86219 ']'
+ preview_file Lightroom
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type Lightroom
+ mime=inode/directory
++ file -b --mime-encoding Lightroom
+ encoding=binary
+ '[' -d Lightroom ']'
+ exec
+ cd Lightroom
+ COLUMNS=80
+ exa -G --colour=always
+ head -n 23
/Users/bastian/.config/nnn/plugins/preview-kitty: line 70: /tmp/nnn-fifo.86219: Interrupted system call
+ : starting 86463
+ '[' '' ']'
+ kitty @ launch --no-response --title 'nnn preview' --keep-focus --cwd=/Users/bastian --env NNN_FIFO=/tmp/nnn-fifo.86455 --env PREVIEW_MODE=1 /Users/bastian/.config/nnn/plugins/preview-kitty README.md
+ : starting 86465
+ '[' 1 ']'
+ '[' '!' -r /tmp/nnn-fifo.86455 ']'
+ preview_file README.md
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type README.md
+ mime=text/plain
++ file -b --mime-encoding README.md
+ encoding=utf-8
+ '[' -d README.md ']'
+ '[' text = image ']'
+ '[' utf-8 = binary ']'
+ exec
+ bat --terminal-width=80 --paging=never --decorations=always --color=always README.md
+ head -n 23
/Users/bastian/.config/nnn/plugins/preview-kitty: line 70: /tmp/nnn-fifo.86455: Interrupted system call

```

**Comment by leovilok** [comment] 2020-06-05 13:07
Interesting ... so when your shell start `exec < "$NNN_FIFO"` it block until `nnn` opens it for writing, which happens only when you start moving the cursor. But while the script is bocked on `exec`, the previewing background job exits, which send a SIGCHILD signal, which interrups `exec` ... and your shell just aborts. I find it very strange for a shell to not handle blocking calls interrupted by background job exit.
I wonder what's your shell now :wink: (I see that your interactive shell is fish, but the non interactive one should be something else: `/usr/bin/env sh -c 'echo $SHELL'`).

In this version, we could fix it by waiting for background jobs before the exec, but I'm not sure how to fix in for the new merged version in the work in #634 ...

Anyways @basbebe, could you try this, and send the trace (same file) if it fails?
http://vgx.fr/preview-kitty-wait-traced

**Comment by basbebe** [comment] 2020-06-05 14:03
@leovilok 

```
~
❯ /usr/bin/env sh -c 'echo $SHELL'
/usr/local/bin/fish

~
❯ sudo /usr/bin/env sh -c 'echo $SHELL'
Password:
/bin/sh
```

`/tmp/preview-kitty-err.log`
```
+ : starting 39520
+ '[' '' ']'
+ kitty @ launch --no-response --title 'nnn preview' --keep-focus --cwd=/Users/bastian/.config/kitty --env NNN_FIFO=/tmp/nnn-fifo.39500 --env PREVIEW_MODE=1 /Users/bastian/.config/nnn/plugins/preview-kitty kitty.conf
+ : starting 39522
+ '[' 1 ']'
+ '[' '!' -r /tmp/nnn-fifo.39500 ']'
+ preview_file kitty.conf
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type kitty.conf
+ mime=text/plain
++ file -b --mime-encoding kitty.conf
+ encoding=utf-8
+ '[' -d kitty.conf ']'
+ '[' text = image ']'
+ '[' utf-8 = binary ']'
+ wait %%
+ bat --terminal-width=80 --paging=never --decorations=always --color=always kitty.conf
+ head -n 23
+ exec
+ read -r selection
+ preview_file /Users/bastian/.config/kitty/kitty.conf.sample
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kitty/kitty.conf.sample
+ mime=text/plain
++ file -b --mime-encoding /Users/bastian/.config/kitty/kitty.conf.sample
+ encoding=utf-8
+ '[' -d /Users/bastian/.config/kitty/kitty.conf.sample ']'
+ '[' text = image ']'
+ '[' utf-8 = binary ']'
+ read -r selection
+ bat --terminal-width=80 --paging=never --decorations=always --color=always /Users/bastian/.config/kitty/kitty.conf.sample
+ head -n 23
+ preview_file /Users/bastian/.config/kitty/theme.conf
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kitty/theme.conf
+ mime=text/plain
++ file -b --mime-encoding /Users/bastian/.config/kitty/theme.conf
+ encoding=us-ascii
+ '[' -d /Users/bastian/.config/kitty/theme.conf ']'
+ '[' text = image ']'
+ '[' us-ascii = binary ']'
+ read -r selection
+ bat --terminal-width=80 --paging=never --decorations=always --color=always /Users/bastian/.config/kitty/theme.conf
+ head -n 23
+ preview_file /Users/bastian/.config/kitty
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kitty
+ mime=inode/directory
++ file -b --mime-encoding /Users/bastian/.config/kitty
+ encoding=binary
+ '[' -d /Users/bastian/.config/kitty ']'
+ read -r selection
+ cd /Users/bastian/.config/kitty
+ COLUMNS=80
+ exa -G --colour=always
+ head -n 23
+ preview_file /Users/bastian/.config/karabiner
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/karabiner
+ mime=inode/directory
++ file -b --mime-encoding /Users/bastian/.config/karabiner
+ encoding=binary
+ '[' -d /Users/bastian/.config/karabiner ']'
+ read -r selection
+ cd /Users/bastian/.config/karabiner
+ COLUMNS=80
+ exa -G --colour=always
+ head -n 23
+ preview_file /Users/bastian/.config/kak
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kak
+ mime=inode/directory
++ file -b --mime-encoding /Users/bastian/.config/kak
+ encoding=binary
+ '[' -d /Users/bastian/.config/kak ']'
+ read -r selection
+ cd /Users/bastian/.config/kak
+ COLUMNS=80
+ exa -G --colour=always
+ head -n 23
+ preview_file /Users/bastian/.config/kak/plugins
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kak/plugins
+ mime=inode/directory
++ file -b --mime-encoding /Users/bastian/.config/kak/plugins
+ encoding=binary
+ '[' -d /Users/bastian/.config/kak/plugins ']'
+ read -r selection
+ cd /Users/bastian/.config/kak/plugins
+ COLUMNS=80
+ exa -G --colour=always
+ head -n 23
+ preview_file /Users/bastian/.config/kak/TRAMPOLINE.txt
+ kill %%
+ clear
++ tput lines
+ lines=23
++ tput cols
+ cols=80
++ file -b --mime-type /Users/bastian/.config/kak/TRAMPOLINE.txt
+ mime=text/plain
++ file -b --mime-encoding /Users/bastian/.config/kak/TRAMPOLINE.txt
+ encoding=utf-8
+ '[' -d /Users/bastian/.config/kak/TRAMPOLINE.txt ']'
+ '[' text = image ']'
+ '[' utf-8 = binary ']'
+ read -r selection
+ bat --terminal-width=80 --paging=never --decorations=always --color=always /Users/bastian/.config/kak/TRAMPOLINE.txt
+ head -n 23
+ exit 0
```

**Comment by jarun** [comment] 2020-06-05 14:07
In case you guys want to do it real time, use https://gitter.im/jarun/nnn

**Comment by leovilok** [comment] 2020-06-05 14:17
@basbebe So you can conform that this version works without crashing?

@jarun I don't use gitter (unless someone really want me to chat there) but I'm always available on IRC with the nick `lvgx` on a few servers including freenode.

**Comment by basbebe** [comment] 2020-06-05 14:18
> @basbebe So you can conform that this version works without crashing?

sorry.

yes, this works!

**Comment by leovilok** [comment] 2020-06-05 14:46
Good, the next step will be to make it work in the version made by @marioortizmanero  in #634, but we can wait until it's integrated.

**Comment by basbebe** [comment] 2020-06-05 14:47
great, thanks!

**Comment by leovilok** [comment] 2020-06-05 17:01
I installed `dash` and I can now reproduce your issue directly.

**Comment by leovilok** [comment] 2020-06-05 23:04
I've found a new fix which should work in @marioortizmanero's version too:
we can just use:
```sh
    cat "$NNN_FIFO" |\
```
instead of:
```sh
    exec < "$NNN_FIFO"
```
I guess that this count as an "useless" use of `cat`, but since `dash`'s `exec` doesn't handle background process exit while it's blocked, it's just more robust.

And we have to remember that `dash` is the default `/bin/sh` on debian (hence probably ubuntu), and now apparently OSX too.
