### ISSUE TITLE
nnn fails to redraw

### ISSUE THREAD

**Issue by dbolgheroni** [jarun/nnn#1067] opened 2021-06-11 21:42 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [X] Operating System: `OpenBSD 6.9-current (GENERIC.MP) #39: Sun May 30 15:59:42 MDT 2021`
- [X] Desktop Environment: `i3 version 4.19.2 (2021-02-27)`
- [X] Terminal Emulator: `XTerm/OpenBSD(367)`
- [X] Shell: `@(#)PD KSH v5.2.14 99/07/13.2`
- [ ] Custom desktop opener (if applicable):
- [ ] Program options used:
- [ ] Configuration options set:
- [X] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

The issue was first reported here tmux/tmux#2726, but it was closed because *tmux* seems to be asking for a resize correctly.

A similar test which the same resize problem occurs generates the following *nnn* log:

```
ln __line__: VERSION=4.1.1
ln __line__: g_tmpfpath=/tmp
ln __line__: tmpfplen=5
ln __line__: home=/home/dbolgheroni
ln __line__: cfgpath=/home/dbolgheroni/.config
ln __line__: cfgpath=/home/dbolgheroni/.config/nnn
ln __line__: selpath=/home/dbolgheroni/.config/nnn/.selection
ln __line__: opener=xdg-open
ln __line__: getenv(envs[ENV_VISUAL])=(null)
ln __line__: getenv(envs[ENV_EDITOR])=(null)
ln __line__: editor=vi
ln __line__: pager=less
ln __line__: shell=/bin/ksh
ln __line__: getenv("PWD")=/home/dbolgheroni/nnn
ln __line__: COLORS=256
ln __line__: COLOR_PAIRS=32767
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=1104017
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/nnn
ln __line__: path=/home/dbolgheroni
ln __line__: __func__=dentfill
ln __line__: *ppdents=0x71692656000
ln __line__: ts2.tv_nsec - ts1.tv_nsec=692004
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni
ln __line__: path=/home/dbolgheroni/Downloads
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=286694
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/Downloads
ln __line__: newpath=/home/dbolgheroni/Downloads/161204_Mastering_the_FreeRTOS_Real_Time_Kernel-A_Hands-On_Tutorial_Guide.pdf
ln __line__: sb.st_mode=33188
ln __line__: pid=23622
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/Downloads
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=332801
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/Downloads
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=317187
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/Downloads
ln __line__: __func__=dentfill
ln __line__: ts2.tv_nsec - ts1.tv_nsec=289466
ln __line__: __func__=redraw
ln __line__: path=/home/dbolgheroni/Downloads
```

The last 3 redraws were forced redraws (`^L`) but *nnn* doesn't actually redraw the text on the screen (text is garbled).

If more information or even screenshots are needed, let me know.

Thank you.

**Comment by Stig124** [comment] 2021-06-11 22:15
Looks like #1050, but it happens all time here, and only on the preview there

**Comment by luukvbaal** [comment] 2021-06-11 22:34
Nah that was an entirely different issue. `preview-tui` has it's own `WINCH` handler, has nothing to do with `nnn` redraws.

I can't seem to reproduce this issue however.

**Comment by luukvbaal** [comment] 2021-06-11 22:38
Seems we are checking `KEY_RESIZE` which is defined in `/usr/lib/curses.h` for me. Idk if this is present on OpenBSD?

**Comment by jarun** [comment] 2021-06-12 04:59
@dbolgheroni please share the steps to reproduce the issue consistently and a video to visualize the problem.

**Comment by jarun** [comment] 2021-06-12 06:41
OK, I see the data available in the other defect.

`nnn` does handle `KEY_RESIZE`.

@0xACE can you please take a look?

**Comment by jarun** [comment] 2021-06-12 06:49
If you see `redraw()`, the first call is:

    getmaxyx(stdscr, xlines, xcols);

which is supposed to get the correct screen dimensions on the next <kbd>^L</kbd> even if it misses the `KEY_RESIZE`.
That comes from the underlyign curses library. I am assuming you see this with `ncursesw`.

However, tagging @rofl0r from `netbsd-curses` in case he can share some insights. If not, we may have to check this with the ncurses devs.

**Comment by jarun** [comment] 2021-06-12 06:51
Also tagging @dankamongmen from `notcurses` library for any hints.

**Comment by jarun** [comment] 2021-06-12 07:30
Took some hints from [here](https://stackoverflow.com/questions/55554703/python-curses-getmaxyx-always-returning-same-value-on-windows).

Please confirm if the issue is fixed on master with the change.

**Comment by 0xACE** [comment] 2021-06-12 14:53
I'm going to be away for the most of the summer all I have is a bluetooth keyboard and a broken phonescreen... So expect a very slow push from me.

It has almost been 1-2 years since I looked at that code, but if i remember correctly: the COL/ROW variables were not guaranteed to work on all systems (or was it key_resize?). So if your attempted fix doesn't work it'd be better to just debug his build and just see what actually is wrong or just read their manuals... @dbolgheroni could you recommend a minimal OpenBSD distribution i can run in a VM?

**Comment by dbolgheroni** [comment] 2021-06-12 16:39
@0xACE, OpenBSD is the entire OS, not just the kernel. So, [OpenBSD](https://openbsd.org) is itself its distribution, with its own packages, package manager, daemons, etc. The latest version is 6.9, which runs without problem on a VM:

https://cdn.openbsd.org/pub/OpenBSD/6.9/amd64/install69.img

**Comment by dbolgheroni** [comment] 2021-06-12 16:50
@jarun, tried last 69926a8eff971655112d950150802f92f8f4423c which includes your fix but didn't see any change in the behavior.

**Comment by jarun** [comment] 2021-06-12 17:00
In that case can you add `resize_term(0, 0);` above this line https://github.com/jarun/nnn/blob/69926a8eff971655112d950150802f92f8f4423c/src/nnn.c#L6755 and see if pressing <kbd>^L</kbd> helps?

**Comment by jarun** [comment] 2021-06-12 18:47
@dbolgheroni please ignore the above comment. Please try with master now. Your issue should be fixed.

**Closed** 2021-06-12 18:47 UTC
Labels: bug

**Comment by dbolgheroni** [comment] 2021-06-12 21:07
@jarun, `^L` works as expected now. Thank you.
