### ISSUE TITLE
how use kitty plugin preview?

### ISSUE THREAD

**Issue by midexe6380** [jarun/nnn#578] opened 2020-05-17 18:53 UTC
in kitty config set option `allow_remote_control yes`
create `/tmp/nnn.fifo`
set `NNN_FIFO=/tmp/nnn.fifo nnn`
set `NNN_PLUG='p:preview-kitty';`
but not working
help me please

**Comment by 0xACE** [comment] 2020-05-17 19:23
I don't have kitty, but the other devs usually respond within 24hours.

Do any of the other preview plugins work at least (The idea is to figure out if `NNN_FIFO` is working correctly for you)

and most importantly, you probably have to be on master, I didn't read the PR for `kitty` support, but it's a good idea if you are checking out the bleeding edge features...

But hold out, preview has been the best thing we've implemented the past year if you ask me.

**Comment by leovilok** [comment] 2020-05-17 19:30
@midexe6380 what happens when you start the plugin (press `;` than `p`), do you see a new kitty pane opening?

**Comment by leovilok** [comment] 2020-05-17 19:38
Basically try:
1. `NNN_FIFO=/tmp/nnn.fifo NNN_PLUG='p:preview-tui' nnn` in any term emulator, then press `;p`, if this doesn't work the issue is related to FIFO/preview stuff
2. in `kitty`, try running `kitty @ launch man man`, if this doesn't open a new pane with a man page open, the issue is probably related to kitty config.

**Comment by midexe6380** [comment] 2020-05-17 20:27
panel opens and closes immediately
(press `;` than `p`)
https://youtu.be/TDSorSve9q8

my kitty.conf
https://termbin.com/1p72

command `kitty @ launch man man` is working (open new pane with man)

when i try run preview-tui
> 1. `NNN_FIFO=/tmp/nnn.fifo NNN_PLUG='p:preview-tui' nnn` in any term emulator, then press `;p`, if this doesn't work the issue is related to FIFO/preview stuff

https://i.imgur.com/wwan1G7.png

**Comment by midexe6380** [comment] 2020-05-17 20:38
Stop. Should be on a master branch? I have 3.1 version.

**Comment by leovilok** [comment] 2020-05-17 20:46
@midexe6380 yes, the NNN_FIFO feature, needed for file preview support, was introduced 2 weeks ago.

I also think that you have NNN_FIFO pointed to a regular file (not a FIFO), just either remove the file (and `nnn` will create a FIFO for you), or create it with `mkfifo`.

**Comment by midexe6380** [comment] 2020-05-17 21:13
is working now
but is not live previews
I can view only one file
https://i.imgur.com/7BZuRyk.png

**Comment by leovilok** [comment] 2020-05-17 21:51
OK, you probably fixed the FIFO file issue, now you'll need to update `nnn` to master.

**Comment by 0xACE** [comment] 2020-05-17 22:22
I'm suspecting he may believe preview means something else

![2020-05-18_00-18-46](https://user-images.githubusercontent.com/1482942/82161478-991ed700-988c-11ea-8d73-3ca165f4f159.gif)

Is it not working like this?

If you need different behavior, chances are you have to re-program it for your needs. The current system is very versatile

**Comment by midexe6380** [comment] 2020-05-18 01:11
is working now 😊
@0xACE 
@leovilok 
Thank you so much.

demo nnn and ranger preview
https://youtu.be/XwDYEfAo8YY

planning to create a key to automatically launch kitty plugin ?
like `nnn --plugin=preview-kitty`
not to press  `;` than `p`

**Comment by jarun** [comment] 2020-05-18 01:51
> planning to create a key to automatically launch kitty plugin ?

Not a bad idea. But you can also press `Alt-P`.

**Comment by jarun** [comment] 2020-05-18 03:36
@midexe6380 check out program option `-P` at commit 1b5c3096caaa6cd903473a69ec0890f40a986967.

**Comment by jarun** [comment] 2020-05-18 03:36
Closing the issue as it is resolved.

**Closed** 2020-05-18 03:37 UTC

**Comment by midexe6380** [comment] 2020-05-18 14:28
i use current kitty version 0.17.4
https://github.com/kovidgoyal/kitty/releases/tag/v0.17.4

plugin is working
but kitty preview function needs stabilization
because when you close nnn, the preview window does not always close
sometimes it closes sometimes no

as a result, the preview window remains open, while nnn is already closed

**Comment by jarun** [comment] 2020-05-18 16:53
@midexe6380 

> but kitty preview function needs stabilization

Please raise an issue on kitty.

**Comment by leovilok** [comment] 2020-05-18 17:56
@midexe6380 oh, I guess it might never close if you never move the cursor, is it the issue?

**Comment by midexe6380** [comment] 2020-05-18 19:05
@leovilok   I don't understand what you mean

**Comment by leovilok** [comment] 2020-05-18 22:12
@midexe6380 in `nnn`, if you start the preview plugin to preview the hovered file, and then immediately exit `nnn` (so you never preview more than 1 file), I think that there is a case where the preview window stays open. (Because `nnn` never opened the write FIFO, so it never closes it)

**Comment by midexe6380** [comment] 2020-05-19 02:25
@leovilok  Do you think this is normal behavior nnn?

**Comment by leovilok** [comment] 2020-05-19 04:29
@midexe6380 no, it's a minor issue, but I just thought about it theorically, is it really the issue you're experiencing?

**Comment by midexe6380** [comment] 2020-05-19 05:28
@leovilok  I don't know. How to check it?

**Comment by 0xACE** [comment] 2020-05-19 11:47
> @leovilok I don't know. How to check it?

by hovering/clicking on another file. basically make sure you select a file AFTER the preview-plugin has started.

Because `nnn` doesn't send anything to `nnn_fifo` until after the preview-plugin has started

**Comment by leovilok** [comment] 2020-05-19 16:35
@midexe6380 I added a FIFO notify on exit in PR #581, this should fix your issue.

**Comment by leovilok** [comment] 2020-05-19 17:42
@midexe6380 the fix is now merged to master (commit https://github.com/jarun/nnn/commit/0c916ae7b024c961df1ab1797035ee80501f66e3)

**Comment by midexe6380** [comment] 2020-05-20 03:08
@leovilok   Amazing!
Thank you very much 🙏
However kitty plugin needs to be stabilized https://github.com/jarun/nnn/issues/582
