### ISSUE TITLE
NNN Freezes when pressing enter on a file, probably trying to open the file wrongly

### ISSUE THREAD

**Issue by ThaDaVos** [jarun/nnn#678] opened 2020-07-14 10:14 UTC
#### Environment details (Put `x` in the checkbox along with the information)

[X] Operating System: Windows 10 -> WSL 2 Ubuntu 18.04
[ ] Desktop Environment: 
[X] Terminal Emulator: TMUX
[X] Shell: Bash
[X] Custom desktop opener (if applicable): Default or Nuke
[ ] Program options used: ...
[ ] Configuration options set: ...
[ ] Issue exists on `nnn` master

#### Exact steps to reproduce the issue
When I open NNN and press enter on a file, probably trying to open it, my whole terminal freezes

**Comment by 0xACE** [comment] 2020-07-14 10:19
Which file are you trying to open? do you havae xdg-open installed in your `PATH` ?

**Comment by ThaDaVos** [comment] 2020-07-14 10:22
It does not open the file itself -> when using xdg-open to open the file it opens it with Chrome for some reason.
The file is just a normal `.sh` file

**Comment by ThaDaVos** [comment] 2020-07-14 10:22
I want to open it with Visual Studio Code instead, as that's my default editor

**Comment by 0xACE** [comment] 2020-07-14 10:46
It's likely opening in `chrome.exe` because `xdg-open` is cancer...

anyhow in your `~/.bashrc` put these atleast
```
export VISUAL=code
export EDITOR=nano
export NNN_USE_EDITOR=1
```

optionally (in addition) you could add: `export PATH=~/pre-bin:$PATH`
and then create your own `xdg-open` script in ~/pre-bin` or replace it with one of the other existing alternatives...

and honestly read the wiki or our docs. `nnn` can't tell what your environment is, you have to provide it yourself. `nnn` seems to be working as intended.

**Comment by ThaDaVos** [comment] 2020-07-14 10:50
Thanks that solved it - but how can I make it so it starts `code` instead of `nano`?
When I change `EDITOR=nano` to `EDITOR=code` it only flickers the screen

**Comment by 0xACE** [comment] 2020-07-14 10:56
I would use the same trick as before with providing a script within your `PATH` making a `wrapper-code` which basically looks like this:

```
#!/usr/bin/env sh
code "$@"  >/dev/null 2>/dev/null &
```

and finally `export EDITOR=wrapper-code`

or maybe you could find better wrappers at https://stackoverflow.com/questions/29971053/how-to-open-visual-studio-code-from-the-command-line-on-osx or google

good luck.

Close this issue if your problem is solved.

**Comment by jarun** [comment] 2020-07-14 13:36
@ThaDaVos please follow the steps here to register visual studio code with `xdg-open` for the correct mime type for sh files.

**Closed by jarun** 2020-07-14 13:36 UTC
Labels: bug

**Comment by ThaDaVos** [comment] 2020-07-14 14:37
If Visual Studio Code was installed normally, I think that would work -> but I'm using WSL 2 so as far as I can find there's no .desktop file available to register

**Comment by 0xACE** [comment] 2020-07-14 14:49
> If Visual Studio Code was installed normally, I think that would work -> but I'm using WSL 2 so as far as I can find there's no .desktop file available to register

copy an existing `*.desktop` file and edit it to adjust for vscode, or copy one form linux ...

**Comment by jarun** [comment] 2020-07-14 14:54
Do you have `xdg-open` in WSL? If not, you can use the method suggested by @0xACE: https://github.com/jarun/nnn/issues/678#issuecomment-658110401

You can also consider using your own custom opener. See `nuke` under plugins.

**Comment by ThaDaVos** [comment] 2020-07-14 15:15
I did that change @jarun as mentioned in https://github.com/jarun/nnn/issues/678#issuecomment-658110401 but it opens inside `nano` -> if I change the editor to `code` it just flickers

**Comment by ThaDaVos** [comment] 2020-07-14 15:16
Fixed it... for some reason I need to full path to my code.exe file else it won't work

**Comment by ThaDaVos** [comment] 2020-07-14 15:18
Now I only have to get it working with the tmux-sidebar plugin... currently the screen shifts one up and then stops -> nothing opens
