### ISSUE TITLE
Question? vim-like -p

### ISSUE THREAD

**Issue by ayoubelmhamdi** [jarun/nnn#1464] opened 2022-08-19 23:27 UTC
how to open two directories,
- first in `cwd 1`
- second in `cwd 2`

**Comment by N-R-K** [comment] 2022-08-20 04:17
duplicate of https://github.com/jarun/nnn/issues/1316 (?)

**Comment by jarun** [comment] 2022-08-20 04:17
If you need to use this frequently, please use sessions.
Otherwise, open from within `nnn`. Try filtering or the _type-to-nav_ mode. You would probably need fewer keypresses to open the directory in another context.

I prefer to avoid more code increasing the binary size and start-up time which are of primary importance to `nnn`.

**Closed by jarun** 2022-08-20 04:17 UTC

**Comment by ayoubelmhamdi** [comment] 2022-08-20 08:53
many task was repeated, so for that, the `autosuggestion` feature is very useful in terminal.
when i press just `n`, is give `nnn dir1 dir2` 
then, i can copy some kinds from `dir1` to `dir2` very easy

can some script do this future? like this
```bash
#!/bin/bash

dir1=${1:-}
dir2=${2:-}

if [[ -z ${dir1} && -z ${dir2} && -d  ${dir1} && -d ${dir2} ]];then
    echo $dir1 > /tmp/dirs
    echo $dir2 >> /tmp/dirs
    nnn # load sesion generated from /tmp/dirs
fi
```
