### ISSUE TITLE
Debian 9: could not locate package nnn 

### ISSUE THREAD

**Issue by longtth** [jarun/nnn#210] opened 2019-02-19 16:33 UTC
Dear jarun,
Thanks for an incredible file manager, I love it so much and have a good time with it on my ubuntu box.  
Today when I work on a new Debian server, I've try to install it using `sudo apt-get update && sudo apt-get  install nnn` it throw me an error: 
```
...
Fetched 19.3 MB in 13s (1,383 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nnn
```
here is my `/etc/apt/sources.list` content
```
deb http://httpredir.debian.org/debian stretch main
deb http://security.debian.org/ stretch/updates main
deb  http://deb.debian.org/debian  stretch main
deb-src  http://deb.debian.org/debian  stretch main

```
What repo should I add to use your package? 
here is my debian info: 
```
bitnami@debian:~/.vim$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch

```

**Comment by jarun** [comment] 2019-02-19 16:39
@szlin please take a look.

**Comment by jarun** [comment] 2019-02-19 18:26
BTW, I can see `nnn` is on Buster and Sid: https://packages.debian.org/search?keywords=nnn&searchon=names&exact=1

**Comment by szlin** [comment] 2019-02-20 10:51
@longtth 

It looks like server issue and it is not related to nnn project.

Please use the sources.list [1] in below.

> deb http://deb.debian.org/debian stretch main
> deb-src http://deb.debian.org/debian stretch main
> 
> deb http://deb.debian.org/debian-security/ stretch/updates main
> deb-src http://deb.debian.org/debian-security/ stretch/updates main
> 
> deb http://deb.debian.org/debian stretch-updates main
> deb-src http://deb.debian.org/debian stretch-updates main

[1] https://wiki.debian.org/SourcesList

**Comment by jarun** [comment] 2019-02-20 14:49
Closing the issue with the above comment.

**Closed by jarun** 2019-02-20 14:49 UTC

**Comment by dud** [comment] 2019-05-07 18:59
I can see this package nnn is available for both Buster and Sid. I'm using the exact sources.list posted by @szlin but I still get the Unable to locate package nnn. I'm using debian stretch.
_:~$ sudo apt-get install nnn
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nnn_

_:~$  lsb_release -a
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch_

**Comment by jarun** [comment] 2019-05-07 19:01
@szlin please check it out.

**Comment by jarun** [comment] 2019-05-07 19:02
@dud also see https://github.com/jarun/nnn/issues/217#issuecomment-469226327.

**Comment by szlin** [comment] 2019-05-10 04:20
@dud Debian supports nnn since Debian 10 (buster), and thus you cannot find nnn in Debian 9 (stretch). The reason why is that  Debian 9 released in 2017 and nnn can only accept in the next version of Debian.

@jarun My previous reply is not correct. The root cause is that nnn only existed in Buster and Sid instead of Stretch, sorry for the confusion.

**Comment by jarun** [comment] 2019-05-10 04:41
@szlin no problem!

**Comment by stupid-genius** [comment] 2019-07-07 22:40
Is there any way to install it on stretch?

**Comment by jarun** [comment] 2019-07-08 02:35
@stupid-genius you can always install the auto-generated package for Debian.

**Comment by stupid-genius** [comment] 2019-07-08 19:55
I'm quite comfortable with Linux, but I'm not sure what that means.  I know that Debian sort of has their own vernacular.  Is that a Debian thing?  What is "the auto-generated package" and where do I find it?

**Comment by jarun** [comment] 2019-07-09 01:13
The latest ones are here: https://github.com/jarun/nnn/releases/tag/v2.5

You have to get `nnn_2.5-1_debian9.amd64.deb`

To install, run: `dpkg -i nnn_2.5-1_debian9.amd64.deb`
