### ISSUE TITLE
Create symlink `@` to selection fails

### ISSUE THREAD

**Issue by amanjitsk** [jarun/nnn#1345] opened 2022-04-19 03:58 UTC
#### Environment details (Put `x` in the checkbox along with the information)

- [x] Operating System: Ubuntu 20.04 LTS
- [x] Desktop Environment: bspwm
- [x] Terminal Emulator: st/kitty
- [x] Shell: zsh
- [x] Custom desktop opener (if applicable): nuke
- [x] Program options used: 
    ```shell
    NNN_SEL=/home/amanjitsk/.config/nnn/selection
    NNN_TRASH=1
    NNN_FIFO=/run/user/1000/nnn.fifo
    NNN_TMPFILE=/home/amanjitsk/.config/nnn/.lastd
    NNN_COLORS=42564256
    NNN_LOCKER=vlock
    NNN_OPTS=cdEfHorQSUx
    NNN_FCOLORS=0B0B04060006060009060B06
    NNN_ARCHIVE=\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$
    NNN_HELP=neofetch
    NNN_OPENER=/home/amanjitsk/.config/nnn/plugins/nuke
    NNN_INCLUDE_HIDDEN=1
    ```
- [x] Configuration options set: `NNN_OPTS=cdEfHorQSUx`
- [x] Plugins are installed
- [x] Issue exists on `nnn` master

#### Exact steps to reproduce the issue

- Select a file/dir that you'd like to create a symlink to
- Go to some **other** directory, and attempt to create a symlink to the
    selection with the same name, with the key sequence `ns@<Return>s` and this fails with the error `File exists`

This operation should not fail, unless I am attempting to create a symlink in
the same directory with the same name. This used to work before, but now, it
now longer allows to create a symlink with the same name. Trying to create
a symlink to a selected file/dir works if `@` is replaced with some other
name, but it is annoying to type out a name, especially when in most cases, I'd like to retain the same name.

Last I checked, the key `@` was used to indicate that the symlink name is the
same as the target, unless this has changed now. I also cannot unfortunately
pinpoint exactly which commit this feature broke (this used to work before),
because I have been ignoring this error for quite some time now.

Best,
Amanjit

**Comment by N-R-K** [comment] 2022-04-19 04:13
Duplicate of #1282

**Comment by amanjitsk** [comment] 2022-04-19 04:29
Ah, I see. I read through the post, but I still don't understand the rationalize behind why the `@` behavior was removed for a single selection. If anything, I thought it would just be a special case. I still think it would be convenient to have that prefix notion for single selection.  Anyways, thanks for pointing me to this!

**Closed** 2022-04-20 14:51 UTC
Labels: bug

**Comment by amanjitsk** [comment] 2022-04-20 17:29
Thanks, just pulled from master, but I don't know if you misunderstood the intent. Pressing `@` on a single selection now creates a symlink with the name `@` (I was hoping `@` would retain the target name, and not a literal `@` name - but at least this commit makes this possible). But I guess I won't re-open the issue as it seems that the decision to get rid of the the prefix notion for a single selection was a deliberate design choice.
